apache/cordova-android

- framework/src/org/apache/cordova/CordovaHttpAuthHandler.java
- framework/src/org/apache/cordova/CordovaPlugin.java
- framework/src/org/apache/cordova/CordovaWebViewClient.java
- framework/src/org/apache/cordova/ICordovaHttpAuthHandler.java
- framework/src/org/apache/cordova/PluginManager.java
https://issues.apache.org/jira/browse/CB-8201
Makes it possible to provide custom pluggabble logic to process auth challenge (for example by installing corresponding plugin, sample implementation: https://github.com/msopentech/cordova-plugin-auth-dialog).
*Motivation*
If you load some resource which requires authentication using android default browser default login dialog appears, but if you try to load the same resource using cordova app then no dialog is shown for user and request is failed w/ 401 Unauthorized. So Currently apps have to provide own JS logic to show web based auth dialog. 
It will be great if Cordova Android offers special functionality (in core or via special interface plugin developers can extend) to automatically show native auth dialog. This is extremely useful in …
> CB-8201 Add support for auth dialogs into Cordova Android

- bin/lib/check_reqs.js
This fixes [CB-9286](https://issues.apache.org/jira/browse/CB-9286) which is a regression from 4bf705a.
> CB-9286 Fixes build failure when ANDROID_HOME is not set.

- bin/templates/cordova/lib/prepare.js
This is a port of https://github.com/apache/cordova-lib/pull/328 to cordova-android. Need to be done in two places since the `prepare` logic was moved to platform.
More details on JIRA: [CB-9844](https://issues.apache.org/jira/browse/CB-9844) and [CB-9736](https://issues.apache.org/jira/browse/CB-9736)
> CB-9844 Remove old .java after renaming activity

- cordova-js-src/platform.js
- framework/src/org/apache/cordova/CallbackContext.java
- framework/src/org/apache/cordova/CordovaInterfaceImpl.java
- framework/src/org/apache/cordova/CordovaPlugin.java
- framework/src/org/apache/cordova/CordovaWebViewImpl.java
- framework/src/org/apache/cordova/CoreAndroid.java
- framework/src/org/apache/cordova/PluginManager.java
- framework/src/org/apache/cordova/ResumeCallback.java
This is a redo of #236 after receiving some feedback. This relates to CB-8917 and CB-9189.
The issue at hand is that plugins can make calls to an external Activity and, if the device is low on memory, there is a chance that the CordovaActivity will get killed in the background causing the plugin to lose its state as well as its context for the callback. Activities in Android typically handle this situation by using `onSaveInstanceState()` and `onCreate()` methods to save and restore state respectively as the Activity is created and destroyed. This solution exposes that lifecycle to plugins, allowing them to save state and have it restored if necessary.
Two new methods are exposed to plugins that they can override to save/restore state.
```java
/**
* Called when the Activity is being …
```
> CB-8917: Added pending plugin callbacks to resume event payload

- bin/templates/project/assets/www/cordova.js
- cordova-js-src/platform.js
Changes the resume event behavior as follows:
1. When the app starts and there is no plugin result to be delivered, the **resume event will not fire** (same as current behavior)
2. When the app is left and then resumed (e.g. press the home button and then return to the app), the **resume event will fire but will not be sticky** (same as current behavior)
3. When the app is recreated after a plugin Activity finishes (i.e. the event payload contains a pending result), the **resume event will fire and will be sticky**
> CB-10498: Resume event should be sticky if it has a plugin result

- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/pluginHandlers.js
- spec/unit/pluginHandlers/handlers.spec.js
This is a supplementary PR for https://github.com/apache/cordova-lib/pull/423 which removes requirement for running prepare to copy plugin's files to `www` dir.
> CB-11022 Duplicate www files to both destinations on plugin add/rm

- bin/templates/cordova/lib/emulator.js
https://issues.apache.org/jira/browse/CB-9489
Only emulators with API level 22+ are affected by this.
Fixed by changing the wait logic: we don't poll every started emulator anymore. Instead, we're launching the emulator on a specific port and poll only this instance, waiting for boot to complete.
> CB-9489 Fixed "endless waiting for emulator" issue

- bin/templates/cordova/lib/prepare.js
When the app name has an apostrophe defined in config.xml, this cause an issue on Android when building
cordova build android result :
```
:processDebugManifest UP-TO-DATE
:processDebugResources/Users/juju/Documents/projects/synchronized/test-cordova/cordova/platforms/android/build/intermediates/res/merged/debug/values/values.xml:4 : AAPT: Apostrophe not preceded by \ (in L'HelloCordova)
FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Applications/android-sdk-macosx/build-tools/20.0.0/aapt'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or …
```
> [CB-8250] fix issue with app_name containing apostrophes

- README.md
Lining it up with https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#installing-the-requirements
As per https://issues.apache.org/jira/browse/CB-12423
> CB-12423: make explicit JDK 1.8 or greater is needed in the README.

- framework/src/org/apache/cordova/BuildHelper.java
- framework/src/org/apache/cordova/PermissionHelper.java
Android
This PR integrates cordova-plugin-compat directly into cordova-android. Going forward you will not need to add this plugin to your project.
Created a new cordova-android project using this branch. Added a custom version of barcode scanner that does not depend on cordova-plugin-compat. When the app runs the permission dialog is displayed properly when I request to scan a barcode and it allows access to the camera when I allow the permission.
> CB-12730: Compat - INTEGRATE

- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Android
Reverts the fix for CB-12015 which is causing more problems than it is fixing.
Create a new project with change. Behaviour reverts to pre CB-12015 changes.
> Revert CB-12015: initial-scale values less than 1.0 are ignored on Android

- bin/templates/cordova/lib/plugin-build.gradle
- bin/templates/project/build.gradle
- framework/build.gradle
Fix install issues with 25.4.0+ google support libraries. As it is, they are not installable, due to move to new repo.
See note at https://developer.android.com/topic/libraries/support-library/revisions.html#25-4-0 for details:
> Important: The support libraries are now available through Google's Maven repository. You do not need to download the support repository from the SDK Manager.
> Update maven repo to include most recent lib versions

- .travis.yml
- appveyor.yml
- bin/templates/cordova/lib/builders/GradleBuilder.js
- package.json
- test/run_java_unit_tests.js
Trying to make it easy for both humans and our CI systems to run the Java unit tests. In particular, I wanted to seamlessly handle building the gradle wrapper and invoking `gradlew test` on both *nix and Windows systems.
Changes include:
- added a node script in the `test/` project directory, `run_java_unit_tests.js`, that wraps up building the gradle wrapper for the test project and invoking the unit tests (`gradlew test`)
- wrapped up running that script in the `npm run java-unit-tests` helper
- include `npm run java-unit-tests` in the top-level `npm test` script
- now runs java unit tests in travis and appveyor
- small refactor in `gradlebuilder.js` to support building the gradle wrapper more easily - kept the defaults and behaviour of gradlebuilder functions as before, just …
> Running Java unit tests more easily

- bin/templates/cordova/lib/emulator.js
- package.json
- spec/unit/emulator.spec.js
Would cause "cannot read property replace of undefined" errors when trying to deploy an Android 8 emulator.
This supersedes #393.
> CB-12981: handle slightly different AVD list output in Android SDK 26.0.2

- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Hi guys. This has happened in some of my apps, not often, but a few times. I also have see some reports on the web.
Take a look at this stack overflow thread for instance:
http://stackoverflow.com/questions/36239052/nullpointerexception-in-cordova-app-reported-by-fabric-sdk
I think that better than just doing a try/catch is just check if the webView is valid/null or not
> CB-6936: fix crash when calling methods on a destroyed webview

- .eslintignore
> CB-12895 : eslint ignoring cordova.js

- bin/templates/cordova/lib/emulator.js
- package.json
- spec/unit/emulator.spec.js
This PR addresses both [CB-13404](https://issues.apache.org/jira/browse/CB-13404) and [CB-13406](https://issues.apache.org/jira/browse/CB-13406).
Summary of changes:
- added tests to the `best_image` method of the emulator command line scripts.
- when comparing project and AVD API levels, sub-optimal matches of the API level would lead to incoherent results for `best_image` since we were applying integer comparisons on strings.
- added required module `android-versions` to `bundledDependencies`
- bumped `android-versions` to 1.2.1 to fix issues when converting API levels and Android semver strings for Android 8.
Ran automated tests.
> CB-13404, CB-13406: `best_image` function fixes when choosing emulator images to deploy to

- bin/templates/project/build.gradle
When 'cdvBuildMultipleApks' is true, 'task.name' can have 'validateSigningArmv7Release' or 'validateSigningX86Release' values.
cordova 7
cordova-android 6.2.3
Fix build.gradle to sign when building with multiple APK is enable.
Test to build with or without signature and with or without multiple APK.
> CB-12802: (android) Fix build.gradle to sign when building with multiple APK is enable.

- bin/templates/cordova/lib/builders/GenericBuilder.js
Android
Fixes master so that we can actually install a non-arch specific APK (Arch-specific APKs like the ones built with Crosswalk are still completely broken)
Tested to make sure it deploys to device.
- [x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
> CB-13530: Fix the utility method for finding the built APK for generic APKs

- bin/templates/cordova/lib/builders/GenericBuilder.js
- bin/templates/project/build.gradle
cordova-android
This PR fixes the build if cdvBuildMultipleApks is set to true by defining `flavorDimensions "default"` in `build.gradle` and by adapting the `findOutputApksHelper` method in `GenericBuilder.js` to recursively scan the `build/outputs/apk` directory for matching candidates.
A positive side-effect of this is that builds with crosswalk will work again :-)
I ran the unit tests and the connectedAndroidTest tests and did manual tests of builds with crosswalk (multiple APKs) and builds without crosswalk (single APK).
> CB-13580: (android) fix build for multiple apks (different product flavors)

- bin/templates/project/build.gradle
android
Add `armeabi`, `arm64-v8a` and `x86_64`
Built and checked for existence of the native libraries in the resulting `.apk`s using `--gradleArg=-PcdvBuildMultipleApks=true` and `--gradleArg=-PcdvBuildArch=<arch>` with `armeabi`, `arm`, `arm64`, `x86`, `x86_64` on a project having https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin installed.
fixes https://issues.apache.org/jira/browse/CB-12291
> CB-12291: (android) Add x86_64, arm64 and armeabi architecture flavors

- bin/templates/project/build.gradle
to the template build.gradle that appends 0 to the versionCode when `cdvBuildMultipleApks` is not set
Android
Adds a Gradle property that, when set to true, establishes a fallback for the 10x bigger versionCodes that were auto-generated even for non-multi-APK builds in cordova-android version before 5.2.0. 
Only local testing. Planned to add some automated testing and documentation but didn't get around to it. Hope someone else will pick it up.
> CB-8976: Added the `cdvVersionCodeForceAbiDigit` property

- framework/src/org/apache/cordova/CordovaInterface.java
- framework/src/org/apache/cordova/CordovaInterfaceImpl.java
A custom engine may live outside of the Activity's lifecycle and the
Activity instance may not always be available. This getter allows
Context accesses in all cases.
> CB-12835: add a Context getter in CordovaInterface

- bin/templates/project/app/build.gradle
Android
Fixes keysigning via properties files
Ran a build with the release-signing.properties file and it signed correctly
> CB-13615: Fix paths to signing properties files

- bin/templates/project/AndroidManifest.xml
- framework/AndroidManifest.xml
Android
Bumps the Min API level ( should have been done on 7.0, but we forgot)
> CB-12914: Forgot to bump AndroidManifest.xml for play store reasons

- framework/cordova.gradle
Android
Fix the location of the config.xml so cdvHelpers.getConfigPreference works
> CB-13721 (Android): fix build apps that use cdvHelpers.getConfigPreference

- bin/templates/cordova/lib/emulator.js
Fixes issue where commands that list images will crash when an image with a version not present in `android-versions` is encountered, as is presently the case with API 27:
```
cordova run android --list
Available android devices:
Available android virtual devices:
LEVEL: null
ERROR: TypeError: Cannot read property 'semver' of null
An unexpected error has occured while running list-emulator-images with code 2: Error: /home/chris/Repositories/acp-guidelines/cordova/platforms/android/cordova/lib/list-emulator-images: Command failed with exit code 2
```
> Prevent crash when unrecognized android version encounterd

- framework/src/org/apache/cordova/NativeToJsMessageQueue.java
- test/app/src/test/java/org/apache/cordova/unittests/NativeToJsMessageQueueTest.java
Android
Fix problem that JavaScript receives ""(empty string) instead of null
if plugin sends null result from new thread.
npm test
> CB-12218: (android) Fix consistency of null result message

- framework/src/org/apache/cordova/CordovaActivity.java
- framework/src/org/apache/cordova/engine/SystemWebChromeClient.java
- framework/src/org/apache/cordova/engine/SystemWebViewClient.java
- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Android
With the release of cordova-android 7.0.0 the minimum API-Level was set to 19. There are a couple of places in the codebase where we have specific logic for older API-levels which are now no longer needed and can therefore be removed.
This PR removes them. It results in (negligible) faster execution and smaller binary sizes, but most importantly less code to maintain.
Ran:
* npm test
* gradlew test
* gradlew connectedAndroidTest
> CB-13800: Drop pre-KitKat specific code

- package.json
Android
Updates `android-versions` to the latest version, 1.3.0, which is aware of the existence of Android API level 27, thanks to https://github.com/dvoiss/android-versions/commit/230957205eeb26e569096251a32179e88a28acfc.
As the `android-versions` npm is a "bundled dependency" this will only
take effect when a new version of `cordova-android` is published, since
bundled dependencies are packed within the npm at publish time, not
automatically fetched as dependencies at publish time (which would have
normally been covered for new installations of cordova-android@7.0.0
thanks to semver caret notation).
* `npm test`
* Confirm that the emulator (i.e. `cordova run android --emulator -d`) will actually launch.
- Presumably covered by the old tests.
> CB-13831: (android) Update `android-versions` to 1.3.0 to support SDK 27.

- bin/templates/cordova/lib/android_sdk.js
[CB-13818]: (android) Update `android_sdk.js` to support Android Oreo (API 26) emulator
cordova-android 7.0x
Fixed the issue described in [CB-13818](https://issues.apache.org/jira/browse/CB-13818)
Tested in my own machine with cordova@7.1.0
> CB-13818: (android) Update android_sdk.js to support Android Oreo 8.0 (API 26) emulator

- framework/src/org/apache/cordova/CordovaResourceApi.java
*Disclaimer: Please review carefully as i'm not a java developer, I just squint a bit and pretend it's C#*
cordova 8.0.0
cordova-android 7.1.0
cordova-plugin-file 6.0.3
Here are details to recreate the issue:
https://github.com/AnthonyWard/cordova-file-plugin-bug
In `cordova-android` the `CordovaResourceApi.java` > `OpenForReadResult` method returns a -1 length in for compressed files.
This has a knock on effect to the `cordova-plugin-file` > `Filesystem.java` > `readFileAtURL` method, causing file corruption as each chunk effectively has no end.
There is a possible fix in the plugin `cordova-plugin-file` already proposed
https://github.com/apache/cordova-plugin-file/pull/217
https://issues.apache.org/jira/browse/CB-13245?jql=text%20~%20%22CordovaResourceApi%22
Or I propose it could be …
> CB-13923 (android) fix -1 length for compressed files

- framework/src/org/apache/cordova/CoreAndroid.java
Android
When the app is started with cdvStartInBackground=true then a pendingPause event is cached until the messageChannel is initialised (before the pause event never reached the webview and it wasn't possible to determine in JS code that the app was started in the background), this change results in the following JS events inside the app:
- pause
- deviceready
As a user you can then store a flag (e.g. app.inBackground) and this can be checked in 'deviceready' handler.
Only manually tested on several Android phones.
> CB-13975: (android) Fix to fire pause event when cdvStartInBackground=true

- bin/templates/cordova/lib/builders/GradleBuilder.js
- bin/templates/cordova/lib/builders/StudioBuilder.js
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
- framework/build.gradle
Android
Bumps up the Gradle version so that we can build with the latest version of Android Studio
Tested building with Android Studio and without Android Studio
- [x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
> CB-14008: Updating Gradle Libraries to work with Android Studio 3.1.0

- bin/templates/cordova/lib/plugin-build.gradle
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
Android
Move google maven repo ahead of jcenter because of some problem to get Google libs from jcenter
> CB-14127: (android) Move google maven repo ahead of jcenter

- bin/templates/cordova/lib/check_reqs.js
Android
- Fix Java version check for Java >= 9
- Checks that we have exactly Java 1.8 since nothing else works with the Android SDK
- Tell the user that we need exactly Java 1.8 if we can't find it
The relevant function was not covered by unit tests to begin with, so I only tested this manually with the following code:
```js
Promise.resolve(
require('./bin/templates/cordova/lib/check_reqs').check_java()
).then(console.log)
```
Output for Java 8 is `1.8.0`, for Java 10 is `10.0.1`.
~~Added automated test coverage as appropriate for this change~~
> CB-14101 Fix Java version check for Java >= 9

- .gitignore
- .travis.yml
- appveyor.yml
- package.json
- test/gradle/wrapper/gradle-wrapper.properties
- test/run_java_unit_tests.js
- test/wrapper.gradle
> Fixes and cleanup for Java tests and CI

- bin/templates/cordova/lib/pluginHandlers.js
Android
Increases old plugin compatibility by adding 'app/src/main' to all plugin source-file tags that didn't include it, so the files are copied to the new Android Studio structure
Tested with `cordova plugin add https://github.com/OutSystems/cordova-plugin-audiorecorder.git` as it uses source-file for images and xml
> CB-14125:(android) Increase old plugin compatibility

- bin/android_sdk_version
- bin/check_reqs
- bin/create
- bin/templates/cordova/build
- bin/templates/cordova/clean
- bin/templates/cordova/lib/install-device
- bin/templates/cordova/lib/install-emulator
- bin/templates/cordova/lib/list-devices
- bin/templates/cordova/lib/list-emulator-images
- bin/templates/cordova/lib/list-started-emulators
- bin/templates/cordova/lib/start-emulator
- bin/templates/cordova/log
- bin/templates/cordova/run
- bin/templates/cordova/version
- bin/update
- package.json
This uses `npm-run-all` to run the two ESLint invocations unconditionally in sequence while still preserving the error code.
> Lint JS w/out extension too

- spec/unit/Adb.spec.js
- spec/unit/AndroidManifest.spec.js
- spec/unit/Api.spec.js
Android
Adds more unit tests for Android.
Since my last PR adding tests went well, I decided to add some more. I have basically gone alphabetically and added tests to give full coverage for `Adb.js` and `AndroidManifest.js`. I may have time later in the next few days to add more tests, but I didn't want to make a huge PR which would take a long time to review.
I also made a small change to the tests for `Api.js`. These tests previously logged `Android Studio project detected`, polluting the test reporter's output. They now no longer do this.
I know the contribution guidelines say to squash PRs into one commit, but in this case, I believe the separate commits make sense. I suppose this could be two (or three) separate PRs. If I should do that next time, please let me know.
Run `npm run …
> More android tests

- bin/templates/cordova/lib/emulator.js
Android (Emulator)
Add fix for 'device still connecting' problem when using android emulator
launching cordova emulate android
> CB-14165 : (android) Fix for device still connecting issues

- CONTRIBUTING.md
Github
Signing the Apache ICLA is no longer required, so I've removed it from `CONTRIBUTING.md`.
> Remove mention of ICLA from contribution guidelines

- bin/templates/cordova/lib/device.js
- bin/templates/cordova/lib/install-device
- bin/templates/cordova/lib/list-devices
- spec/unit/device.spec.js
Android
The main point of this PR is to increase test coverage of `device.js`. It's gone from 0% to 100% coverage. :)
Since I was going through `device.js` and figuring out how it works, I figured it was a good time to replace Q with native promises, as mentioned in [CB-14158](https://issues.apache.org/jira/browse/CB-14158). I hope this is OK!
- Ran device-related commands
- Ran unit tests
> Device: Add unit tests and remove Q

- bin/templates/cordova/lib/emulator.js
- bin/templates/cordova/lib/install-emulator
- bin/templates/cordova/lib/list-emulator-images
- bin/templates/cordova/lib/list-started-emulators
- bin/templates/cordova/lib/start-emulator
- spec/unit/emulator.spec.js
Android
This is pretty much the same as the devices PR (#462). I have increased the test coverage for `emulator.js` (now at 89%). As with the devices PR, this also removes Q and replaces it with native Promises. It looks like all the uses of `fin` or `finally` are all in tests, and most of them were in `emulator.spec.js`. Refactoring the tests meant they were no longer necessary. The other thing to be aware of is other parts of Cordova expecting Q-like promises. In this case, a few other files were expecting to be able to use `done`, but they could be identically replaced with `then` or `catch`.
There is probably some refactoring that could be done on `emulator.js`. The `install` function has custom functionality due to an old ticket which references Android 2.2 (!). I reckon this could …
> Emulator: Add unit tests and remove Q

- package.json
Android
- pin some more bundled dependencies to clear the red highlights in `npm outdated --depth=0`
- `npm audit` with npm@6.1.0 (latest version) shows 0 vulnerabilities
- `npm i && npm t` works on both deprecated Node.js 4 (npm 2.15.11) & Node.js 8 (npm 5.6.0)
- using `cordova platform add brodybits/cordova-android#cb-14145-pin-some-more-bundled-deps-in-patch-only` to add platform to new Cordova project and test on Android device using `cordova run android --device` succeeds on the following Node.js versions:
- deprecated Node.js 4 (npm 2.15.11)
- Node.js 8 (npm 5.6.0)
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this …
> CB-14145 pin some more bundled deps in 7.1.x patch only

- framework/src/org/apache/cordova/CordovaWebViewImpl.java
Android
Fixes #473 
Manual verification that `CordovaWebViewImpl.showWebPage` given file urls do not initiate an external intent request that crashes the app for Android 7+ devices.
> Fixes apache/cordova-android#473: Do not attempt an activity for internal url loads

- bin/templates/cordova/lib/android_sdk.js
- spec/unit/AndroidProject.spec.js
- spec/unit/android_sdk.spec.js
Android
This is the last unit test PR for today, I promise! The `AndroidProject` tests were originally in #458. This PR also contains increased test coverage for `android_sdk.js`. I have also refactored that to remove `Q`, as with the other PRs I submitted today.
Run unit tests
> Unit tests for android_sdk and AndroidProject

- bin/lib/create.js
- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/cordova/lib/builders/builders.js
- bin/templates/cordova/lib/emulator.js
- bin/templates/cordova/lib/pluginHandlers.js
- bin/templates/cordova/lib/run.js
- spec/unit/AndroidProject.spec.js
- spec/unit/builders/builders.spec.js
- spec/unit/create.spec.js
- spec/unit/pluginHandlers/handlers.spec.js
- spec/unit/run.spec.js
Android
Fixes, refactors, and improves the build and run process that came from the builder refactor.
- General Code Refactor
- Removed builder type argument from getBuilder API
- Removed any reference of conditional statements around builder type
- Remove plugin handler install and uninstall option flag android_studio
- Remove --gradle flag references
- Fixed plugin handler install and uninstall pathing issues
- Use the nobuild flag option to control the run build.
- Updated test spec to reflect the changes.
> Fixes build & run related bugs from builder refactor

- bin/templates/project/app/build.gradle
This PR fixes issue [#489](https://github.com/apache/cordova-android/issues/489)
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~
Resolves #489
> Incorrect default sdk version issue fix

- bin/templates/cordova/lib/builders/ProjectBuilder.js
android
generates gradle dependencies in the `build.gradle` from `<framework>` elements found in the `plugin.xml` as the new `implementation` dependencies instead of deprecated `compile` dependencies
ran `npm run test`
- [✘] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
Created a github Issue: https://github.com/apache/cordova-android/issues/485
- [✓] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [✓ ] Added automated test coverage as appropriate for this change.
None were needed
There are some more references to `compile` dependencies in other files but I left them alone bacause I am not sure what they are used for, see: …
> GH-485: (android) Replace deprecated "compile" with "implementation"

- framework/build.gradle
- spec/fixtures/android_studio_project/build.gradle
- test/build.gradle
> Always put the Google repo above jcenter

- bin/create
- bin/lib/create.js
- spec/unit/create.spec.js
Android
When platform is installed though CLI, `cordova platform add android`, the copy node_modules step is no longer valid as dependencies are now at the project level.
The step is required only when the create binary from the platform repo is called.
https://github.com/apache/cordova/issues/32
- npm t
> Only copy platform node_modules when created by binary

- cordova-js-src/exec.js
to work properly on Android Pie
was introduced in dc0bfeb0c (CB-11828)
Not needed since Android JellyBean (4.0-4.3) is no longer supported ref: <https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#requirements-and-support>
Credit goes to pradiv-kumar for raising the issue in #534 and proposing the original solution in #535.
Note that cordova.js should be regenerated by cordova-coho as described in: <https://github.com/apache/cordova-coho/blob/master/docs/platforms-release-process.md>
I would like to get this change into 7.1.x as well.
Resolves #534
Closes #535
> Remove obsolete check for JellyBean (GH-534)

- bin/templates/project/app/build.gradle
- android
- re-add the cast for cdvMinSdkVersion this was in already included in a previous release but get lost [6.4.x/bin/templates/project/build.gradle#L123](https://github.com/apache/cordova-android/blob/6.4.x/bin/templates/project/build.gradle#L123)
- none
> (android) add missing cast for cdvMinSdkVersion

- bin/templates/project/app/build.gradle
- android
- solves issue #552. Therefor include the build-extras.gradle from `platforms/android/`
- If requested I can change this pull request to check on both places `platforms/android/` and `platforms/android/app/` 
- in a local build environment
> #552: (android) check for build-extras.gradle in the app-parent directory

- package.json
This change should to give us a green build again.
Rationale is that the eslint update introduced in 393dad6349d8df55d8fca7d3e5014f36dfa4610c checks most of the files under `bin` and will not accept JavaScript that uses double-quotes for strings. The workaround in 393dad6349d8df55d8fca7d3e5014f36dfa4610c was to change the generated `bin/templates/cordova/version` file to use single-quotes in the version string.
But since cordova-coho will regenerate `bin/templates/cordova/version` with double-quotes when updating the version number, we need a different solution.
This is a quick workaround solution. I won't have a problem if anyone wants to propose an improved solution. Alternative may be to update cordova-coho to generate version file with single-quotes.
> Ignore version file in eslint to resolve build error

- package.json
to resolve red entries from npm outdated, in 7.1.x only (**not wanted** in `master` branch):
```
Package            Current  Wanted  Latest  Location
_______            _______  ______  ______  ________
big-integer         1.6.32  1.6.36  1.6.36  cordova-android
path-is-absolute     1.0.1   2.0.0   2.0.0  cordova-android
semver               5.5.0   5.6.0   5.6.0  cordova-android
```
Will be merged (as a self-approved change) into 7.1.x release once build is green to unblock the patch release.
> Mark some 7.1.3 bundled dependency versions

- .travis.yml
- appveyor.yml
- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/cordova/lib/plugin-build.gradle
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
- bin/templates/project/legacy/build.gradle
- framework/build.gradle
- framework/gradle/wrapper/gradle-wrapper.properties
- framework/src/org/apache/cordova/CoreAndroid.java
- framework/src/org/apache/cordova/engine/SystemCookieManager.java
- framework/src/org/apache/cordova/engine/SystemWebChromeClient.java
- framework/src/org/apache/cordova/engine/SystemWebViewClient.java
- spec/fixtures/android_studio_project/app/build.gradle
- test/app/build.gradle
- test/build.gradle
- test/wrapper.gradle
Android
* Updates to latest version of the [Android gradle plugin](https://developer.android.com/studio/releases/gradle-plugin#3-2-0) (3.2.0)
* Updates gradle to the minimum version required by that plugin (4.6)
* Fixes a gradle warning about LeftShift Closure being deprecated
* Fixes a gradle warning about publishNonDefault being deprecated
* Uses the `google()` repo syntax to reference the Google maven repository
* Updates the Github/project URLs for maven artifacts
* Fixes a handful of deprecation warnings happening inside the CordovaLib classes
In theory, this should fix the NDK issues reported in #504 due to outdated gradle versions.
Nothing yet :upside_down_face:
> Gradle updates

- bin/lib/create.js
We have this of the package name. It only outputs that the current one is bad, not what the current one actually is. Added an output of the current one to the error.
> Output current package name if package name can't be validated

- bin/templates/cordova/lib/pluginHandlers.js
- spec/fixtures/org.test.plugins.dummyplugin/plugin.xml
- spec/unit/pluginHandlers/handlers.spec.js
(subdirectories) such as "appco", with unit tests to verify correct operation
Needed for @katzer plugins that use `de/appplant` subdirectory, for example:
* <https://github.com/katzer/cordova-plugin-local-notifications>, with `target-dir="src/de/appplant/cordova/plugin/notification"`
* <https://github.com/katzer/cordova-plugin-badge>, with `target-dir="src/de/appplant/cordova/plugin/badge"`
* <https://github.com/katzer/cordova-plugin-background-mode>, with `target-dir="src/de/appplant/cordova/plugin/background"`
Also needed for `cordova-plugin-inappbrowser`
Resolves #571
> Resolve issue with plugin target-dir="app*" subdirs

- bin/templates/cordova/lib/pluginHandlers.js
- spec/fixtures/org.test.plugins.dummyplugin/plugin.xml
- spec/unit/pluginHandlers/handlers.spec.js
Let's start fresh!
This is the rebase of my old PR #576 coming from #575 on the master branch as encouraged.
Basically I have separated bloc that was handling new app directory structure from the old one. Plus I have rewrite tests with RegExp allowing buggy forms with or without `/` at the end.
Plus all (hope so) code reviews from @brodybits.
- new: `app`, `app/`, `app/whatever`
- old: `src`, `src/`, `src/whatever/source`, `libs`, `libs/`, `libs/whatever/bin`
- buggy: `src/myappsomething/source`, `appsomething/source`
Like my original issue with: [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications/blob/6d1b27f1e9d8e2198fd1ea6e9032419295690c47/plugin.xml#L145-L147). Try it:
```
$ cordova plugin add cordova-plugin-local-notification
```
#577, …
> Rewrite install dir resolution for legacy plugins

- bin/create
- bin/lib/create.js
- spec/unit/create.spec.js
android
- Reverts PR #536 (Only copy platform node_modules when created by binary)
- Replace implementation to copy the platform node_modules only when the folder exists.
https://github.com/apache/cordova/issues/32
- npm run eslint
- npm run unit-tests
> Copy node_modules if the directory exists

- .gitignore
- bin/templates/cordova/build
- bin/templates/cordova/clean
- bin/templates/cordova/lib/Adb.js
- bin/templates/cordova/lib/AndroidManifest.js
- bin/templates/cordova/lib/device.js
- bin/templates/cordova/lib/emulator.js
- bin/templates/cordova/lib/log.js
- bin/templates/cordova/lib/prepare.js
- bin/templates/cordova/run
- bin/update
- package.json
- spec/coverage.json
- spec/unit/Adb.spec.js
- spec/unit/config/GradlePropertiesParser.spec.js
- spec/unit/create.spec.js
- spec/unit/emulator.spec.js
- spec/unit/pluginHandlers/handlers.spec.js
- spec/unit/prepare.spec.js
- spec/unit/run.spec.js
android
This PR contains final preparations for the Cordova 9 release goals. 
See [Cordova 9 Release Plan](https://github.com/apache/cordova/issues/10).
- Remove unused promise-matchers dependency
- Bumped `cordova-common@^3.1.0`
- Bumped Dev Dependencies with ESLint Correction
- `eslint@^5.12.0`
- `eslint-config-semistandard@^13.0.0`
- `eslint-config-standard@^12.0.0`
- `eslint-plugin-import@^2.14.0`
- `eslint-plugin-node@^8.0.1`
- `eslint-plugin-promise@^4.0.1`
- `eslint-plugin-standard@^4.0.0`
- `jasmine@^3.3.1`
- `rewire@^4.0.1`
- Updated Dependencies
- `elementtree@^0.1.7`
- `nopt@^4.0.1`
- `properties-parser@^0.3.1`
- Replace istanbul dependency with `nyc@^13.1.0`
- `package.json` cleanup
- Dropped `npm-run-all`
- `npm t`
- eslint
- coverage (unit testing)
- java unit test
- [Travis …
> Android Platform Release Preparation (Cordova 9)

- bin/templates/cordova/lib/check_reqs.js
- fix download link
- put download link on its own line
- no punctuation at the end of the download link
(fixes #618)
- no extra newline at the end
- extra newline spacing in case JAVA_HOME is invalid
in response to #618
I hope we can get this in before we cut the next major release for Cordova 9 (apache/cordova#10).
> javac error message fixes in requirements check

- bin/templates/cordova/lib/check_reqs.js
Fixing the error message in response to discussion in #618.
I am not a super JDK 8 expert, would appreciate some feedback if my proposal looks good or not.
P.S. Fixed in another place in response to <https://github.com/apache/cordova-android/pull/619#discussion_r248364947>.
> Fix requirements error messages for JDK 8

- bin/templates/cordova/lib/check_reqs.js
Every platform
Add a log that clarifies the Java validation
No testing needed, this just adds a `console.log` call.
> Add missing log to Java version check

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
- framework/build.gradle
- test/build.gradle
- test/wrapper.gradle
(Gradle 4.10.1 or higher is needed for Android Studio 3.3.0 ref: <https://developer.android.com/studio/releases/gradle-plugin#3-3-0>)
I hope this will be part of the upcoming major release for Cordova 9 (apache/cordova#10).
For the following issues:
- #634 - Update Gradle classpath for Android Studio 3.3
- #596 - Support Gradle 4.9+
I think it would be ideal to update to Gradle 5.1, not convinced we should squeeze this into Cordova 9.
P.S. I verified that no issues were introduced when I tested this change with `cordova-mobile-spec`.
> Android build tools 3.3 & Gradle 4.10.3 update

- bin/templates/cordova/lib/check_reqs.js
This is a quick fix. Purpose is that upcoming major release of cordova-android should **not** depend on deprecated behavior as discussed in #617.
TODO:
FUTURE TODO:
- cleanup
- more elegant
> Quick fix to support ANDROID_SDK_ROOT

- bin/lib/create.js
- bin/templates/cordova/lib/AndroidManifest.js
- bin/templates/cordova/lib/prepare.js
- package.json
- spec/unit/AndroidManifest.spec.js
needed to quickly resolve bug #666 in order to continue with the major release as part of Cordova 9 (apache/cordova#10)
as agreed in the following thread: <https://lists.apache.org/thread.html/aad8b9e6bd47a8401f14d00d960174a2c0cb78f8d8e397791cdf916e@%3Cdev.cordova.apache.org%3E>
> Revert "Remove uses-sdk from AndroidManifest.xml (#664)"

- test/wrapper.gradle
Android
Cordova 9's Release Process
- Adds the missing license header.
Not required
> Added Missing License Headers

- spec/unit/check_reqs.spec.js
none
There was a change in how the export var ANDROID_HOME is being set to follow Android documentation. 
The existing tests which tested an alternative way of find ANDROID_HOME on top of what is in Android documentation were not updated.
The changes were valid and follows Android's documentation, therefore updating the tests were the appropriate solution.
- Local Testing
- CI Testing
> Updated ANDROID_HOME Test to Follow #656 Change

- bin/templates/cordova/Api.js
android
See #690 : The ConfigParser passed in by cordova-lib is constructed from the cordova-common version that cordova-lib is using, rather than the one that cordova-ios is using.
Initialize the ConfigParser at the platform API level so that it uses the expected version.
All unit tests pass.
> Run prepare with the correct ConfigParser version

- framework/src/org/apache/cordova/engine/SystemCookieManager.java
Android
When building, there's a deprecation warning printed about `SystemCookieManager.java uses or overrides a deprecated API.`
Added the correct annotation to silence the warning.
Built an app and no deprecation warning was printed.
> Fix deprecation warning in SystemCookieManager

- bin/lib/create.js
- bin/templates/cordova/lib/AndroidManifest.js
- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/config/GradlePropertiesParser.js
- bin/templates/cordova/lib/prepare.js
- bin/templates/project/AndroidManifest.xml
- bin/templates/project/app/build.gradle
- bin/templates/project/legacy/build.gradle
- framework/AndroidManifest.xml
- framework/build.gradle
- package.json
- spec/unit/AndroidManifest.spec.js
- spec/unit/config/GradlePropertiesParser.spec.js
- spec/unit/create.spec.js
- spec/unit/run.spec.js
android
- Fix https://github.com/apache/cordova-android/issues/675
- Improve ability to set build arguments.
- Remove `<uses-sdk>` from `AndroidManifest.xml` (`minSdkVersion`, `maxSdkVersion`, and `targetSdkVersion`)
- Remove `AndroidManifest` setter and getters for `minSdkVersion`, `maxSdkVersion`, and `targetSdkVersion`
- Updated `compileSdkVersion`
- Remove spec tests.
- Improve ways of setting build SDK values:
- minSdkVersion
- maxSdkVersion
- Added build flag (will set command-line argument and take priority)
- Added `config.xml` `<preference>` name `android-maxSdkVersion` (Updates `gradle.properties`)
- targetSdkVersion
- Added build flag (will set command-line argument and take priority)
- Added `config.xml` `<preference>` name `android-targetSdkVersion` (Updates …
> Improve Gradle Build Arguments

- framework/build.gradle
android
To be able to release the Cordova Android Framework to JFrog Bintray.
Was not able to release the framework to Bintray because of build failures.
```
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
> Task :packageReleaseResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':_internal_aapt2_binary'.
> Could not find com.android.tools.build:aapt2:3.3.0-5013011.
Searched in the following locations:
- file:/Android/sdk/extras/m2repository/com/android/tools/build/aapt2/3.3.0-5013011/aapt2-3.3.0-5013011.pom
- file:/Android/sdk/extras/m2repository/com/android/tools/build/aapt2/3.3.0-5013011/aapt2-3.3.0-5013011-osx.jar
- …
```
> Added allprojects repositories to Framework Build Gradle

- bin/lib/create.js
- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/builders/builders.js
Before this change, the following would fail if `cordova-android` or one of its dependencies are not resolvable from `dir`:
```js
require('cordova-android').createPlatform(dir, configParser, null, events)
```
This happens for example if you want to setup a platform-centered App from scratch. In my case I wanted to create a project in a temp folder during `plugman` test setups in `cordova-lib`.
The problem is, that during project creation `cordova-android` requires some of the modules that have been checked-out to the project directory instead of the ones relative to the running modules (looking at the actual changes will probably clarify what I'm trying to say here).
Instead of switching to the checked-out modules in the created platform-project, we simply use the identical modules …
>  Do not explicitly require modules from project directory

- .travis.yml
CI is currently broken (noticed in https://github.com/apache/cordova-android/pull/764), probably because Travis updated their images:
```
$ yes | sdkmanager tools > /dev/null
/home/travis/.travis/functions: line 104: sdkmanager: command not found
The command "yes | sdkmanager tools > /dev/null" failed and exited with 127 during .
```
We already updated the [`.travis.yml` of paramedic](https://github.com/apache/cordova-paramedic/blob/master/.travis.yml) to solve similar problems, so I used that as a template to get this one here working again as well. Restructed and reformatted the file along the way as well - but no functional changes.
> ci(travis): Fix Android SDK

- package.json
This resolves a `npm audit` warning. Build on AppVeyor & Travis CI seem to be OK on my fork.
I hope we can get this proposal approved and merged asap.
/cc @breautek
> nyc@14 update in devDependencies

- spec/unit/run.spec.js
Android tests
Fixes jasmine output on NodeJS 12.
Fixes #768 
Rewiring the `process` object no longer works as of NodeJS 12. However you can still rewire members of the `process` object. This PR rewires individual `process` members as required by the test, instead of rewiring the `process` object entirely.
I've ran npm test and observed full jasmine output on Node 12. Note, due to another issue as reported #767 here, there is still 1 test failing on NodeJS 12.
I've also ran the tests successfully on NodeJS 10.
> rewire workaround for NodeJS 12

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- spec/unit/builders/ProjectBuilder.spec.js
The existing implementation of this function gives a different order depending on the behavior of `Array.prototype.sort()`, which has led to a test failure on Node.js 12 (see apache/cordova-android#767).
This update gives a consistent sort order, regardless of the JavaScript engine implementation, now succeeds on Node.js versions 6, 8, 10, and 12.
Resolves #767
I hope this explanation is clear enough. If anyone can think of a better explanation or has any criticism, feedback would be much appreciated.
For reference:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
/cc @breautek
> Consistent order from ProjectBuilder.apkSorter

- .travis.yml
to avoid errored Travis CI build on Node.js 12 (see WIP PR #770)
> ci(travis): set `dist: trusty` in `.travis.yml`

- spec/unit/android_sdk.spec.js
- spec/unit/run.spec.js
Fix for the problem described in https://github.com/apache/cordova-android/pull/778#issuecomment-511229607
Properties that are replaced with `spyOn` are restored after each test. The manually set spies that existed previously clobbered the `console.log` property permanently. This broke the test output with the new reporter.
> Do not clobber console.log to spy on it

- spec/unit/run.spec.js
According to the last section _Dot notation_ in the [`rewire` docs](https://www.npmjs.com/package/rewire#caveats), the code from #774 permanently clobbers various properties on the `process` global. This PR fixes #768 without permanently altering `process`.
CC @breautek
> Do not clobber process properties with test mocks

- bin/lib/create.js
- spec/unit/create.spec.js
This seemingly fixed a spurious error in `spec/unit/create.spec.js` that was occurring on my system.
> Properly handle promise in create script

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- package.json
- spec/unit/builders/ProjectBuilder.spec.js
When reviewing #779 I had a hard time understanding what the behavior of `apkSorter` was. I find that is a common issue with complex sort callbacks in JavaScript.
IMHO it's often makes for way more readable and less repetitive code to have a `sortBy` style approach. That's what I implemented in this PR for `apkSorter`.
Implement `apkSorter` in a `sortBy` style using the `compare-func` module.
I used the existing unit tests. One of them had to be fixed, since it stubbed `fs.statSync` incorrectly (`mtime` is a `Date`, not a timestamp)
> Simplify apkSorter using compare-func package

- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/PackageType.js
- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/cordova/lib/run.js
- package.json
- spec/unit/builders/ProjectBuilder.spec.js
- spec/unit/run.spec.js
-  Android
This PR adds support to build android bundle (aab) files.
Fixes:  #729 
~Adds an `--bundle` flag to the `cordova build` command. If present, cordova will do the necessary steps to run the `gradlew bundleDebug` command (or `gradlew bundleRelease` if `--release` flag is present)~
Accepts `packageType` property from `build.json`, or optionally the `--packageType=apk|bundle` command line argument. The `packageType` property was chosen to keep consistency with the iOS platform. 
This PR does not change the current build commands. Building APKs is still necessary for deploying apps to test devices, or of course to upload to the Google Play store using the traditional way. Bundle files are *exclusively* for deploying to Google Play Store. 
You can however use the google provided …
> feat: Build app bundles (.aab files)

- bin/templates/project/AndroidManifest.xml
Android
This change stops the webview from restarting when the activity window resizes while using Android's split-screen feature.
Fixes #799
This change adds some new attributes to the default list of `configChanges` including:
> The current available screen size has changed.
This represents a change in the currently available size, relative to the current aspect ratio, so will change when the user switches between landscape and portrait.
> The screen layout has changed — a different display might now be active.
>The user interface mode has changed — the user has placed the device into a desk or car dock, or the night mode has changed. For more information about the different UI modes, see [UiModeManager](https://developer.android.com/reference/android/app/UiModeManager.html).
All of …
> Stop webview from restarting when activity resizes

- framework/src/org/apache/cordova/CordovaActivity.java
Related to issue #722.
Requesting the focus explicitly actually makes the child WebView to move the focus to the first visible focusable element on the page. This makes it impossible to simply let the WebView restore the focus to the last focused element, before the activity was paused. To prevent this problem on devices other that the Samsung Galaxy Note 3, only request the focus if necessary (it might as well be possible that the original fix is not needed anymore on newer versions of Android and/or WebView).
> Don't request focus explicitly if not needed

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- spec/unit/builders/ProjectBuilder.spec.js
Android
Fixes the `cordova clean` command, a reprecussion bug from https://github.com/apache/cordova-android/pull/764
Fixes https://github.com/apache/cordova-android/issues/813
Due to some code style refactoring, it became possible for the `buildCmd` to stay `undefined`, when it used to default to the incoming parameter `cmd` value. This fixes `ProjectBuilder.getArgs` to fallback to `cmd` value if it doesn't enter in any `if` conditions.
`npm test` & manually testing.
~Note that at the time of working on this issue, master currently did not pass `npm test`. So I have "all new and existing tests pass" checkbox unchecked and checking that box is blocked by https://github.com/apache/cordova-android/issues/814~
> Bugfix: Fixes clean command

- framework/src/org/apache/cordova/engine/SystemWebChromeClient.java
Android
Allows filepicker to select multiple files.
Checked locally
Tested on following devices:
- Moto G5 (Android 7.0)
- Nexus 5X (Android 8.1)
- Samsung Galaxy Tab S4 (Android 8.1)
- Sony Xperia XZ2 Compact (Android 9.0)
- Nexus 7 (Android 6.0.1)
- Sony Xperia Z2 (Android 5.1.1)
The multiple file selection works basically, but behaves different on different devices/software.
On the Moto G5 and Samsung Tab it behaves like expected. Simply use long press (on file explorer, media-gallery, etc ) to start multiple selection.
The Nexus starts the filepicker with multiple selection enabled without using long-press.
- normal file-picker: Works like expected
- Google pictures-app: Starts with multiple selection enabled
- Samsung Gallery: Multiple selection does not work when using as filepicker …
> GH-621 android: Added multiple selection for filepicker

- package.json
Update dependencies (minor bump) for Cordova Android minor release 8.1.0
* Bump Dependency
* `android-versions@^1.3.0` to `android-versions@^1.4.0`
* `cordova-common@^3.1.0` to `cordova-common@^3.2.0`
* `q@^1.4.1` to `q@^1.5.1`
`shelljs` was intentionally left at `^0.5.3`. Bumping caused test failures and would require additional investigation. I was able to fix for Travis CI but there were pathing separator issue within AppVeyor.
* `npm t`
> chore: bump dependencies for release 8.1.0

- framework/src/org/apache/cordova/engine/SystemCookieManager.java
/
The comment seemed aggressive and doesn't add any info or seems to have any purpose.
/
> chore: removed comment that serves no purpose

- bin/templates/cordova/lib/builders/ProjectBuilder.js
When building the project by running `gradlew`, we filter its output on `stderr` to omit a specific diagnostic message. This complicated refactorings in the past and also affects upcoming refactorings regarding `Q` and `superspawn`.
The [reason this code exists](https://issues.apache.org/jira/browse/CB-9971) is a weak one IMHO. The Visual Studio integration deemed the build to have failed if anything has been output on `stderr`. Thus the aforementioned diagnostic message on `stderr` caused successful builds to count as failed ones.
IMHO, the current behavior should be removed for various reasons:
- Diagnostics on `stderr` are not uncommon, so the success of the command should be determined from the returned `Promise` or the process' exit code respectively
- Unclear if code works correctly …
> Don't filter gradle's stderr anymore

- bin/templates/cordova/lib/Adb.js
- bin/templates/cordova/lib/android_sdk.js
- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/cordova/lib/check_reqs.js
- bin/templates/cordova/lib/device.js
- bin/templates/cordova/lib/emulator.js
- bin/templates/cordova/lib/log.js
- package.json
- spec/e2e/plugin.spec.js
- spec/unit/Adb.spec.js
- spec/unit/android_sdk.spec.js
- spec/unit/builders/ProjectBuilder.spec.js
- spec/unit/device.spec.js
- spec/unit/emulator.spec.js
- test/run_java_unit_tests.js
https://github.com/apache/cordova/issues/16
Includes commit from #860 (will rebase ASAP). Depends on #832 and #861.
Replace `superspawn` & `child_process` usage with `execa`.
- `npm t`
> chore: replace superspawn & child_process with execa

- bin/android_sdk_version
- bin/check_reqs
- bin/create
- bin/lib/create.js
- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/Adb.js
- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/check_reqs.js
- bin/templates/cordova/lib/prepare.js
- bin/templates/cordova/lib/run.js
- bin/templates/cordova/log
- bin/update
- package.json
- spec/unit/Api.spec.js
- spec/unit/builders/ProjectBuilder.spec.js
- spec/unit/check_reqs.spec.js
- spec/unit/create.spec.js
- spec/unit/run.spec.js
- test/run_java_unit_tests.js
- Drop `q` module for native promises
- https://github.com/apache/cordova/issues/7
- Remove all `q` usages
- `npm t`
- [Travis CI](https://travis-ci.org/erisu/cordova-android/builds/589772396)
- [AppVeyor](https://ci.appveyor.com/project/erisu/cordova-android/builds/27678088)
**Notice:** Node 6 and 8 tests in Travis CI and AppVeyor fails. This PR is intended for next major as it uses APIs from Node `>=10`. PR https://github.com/apache/cordova-android/pull/832 will be required first.
> chore: drop q module

- .travis.yml
- appveyor.yml
- bin/templates/project/build.gradle
- framework/project.properties
- spec/fixtures/android_studio_project/app/build.gradle
- test/app/build.gradle
Android
Increases the default target/compile SDK version to 29, up from API level 28.
Fixes #830 
Changed build tools to version 29.0.2
changed target SDK to 29
Changed compile SDK to 29
Changed the tests to use version 29.
Ran `npm test`
> Increased default target sdk to 29

- .gitignore
None
Eclipse buildship `.project` files are being added to several directories automatically from my code editor (VS Code) when working on `cordova-android` tasks. I think it makes sense for these files to be git ignored.
Added `**/.project` line in `.gitignore`
> Ignore auto-generated eclipse buildship files

- framework/cordova.gradle
Android
Fixes #708
I changed the regular expression for versions of build tools in **cordova.gradle** file in order to accept all possible versions. And I removed the tag of release life cycle in version string when comparing them.
> 29.0.0-rc1 => 29.0.0
I built an example project with both Android SDK Build-Tools **28.0.0** and **29.0.0-rc1**.
> Support SDK versions with pre-release identifiers

- bin/templates/project/app/build.gradle
- framework/cordova.gradle
To finish off the change requests and close out PR #438 
closes: #438
What this PR does:
1. Cherry-picks commit changes from #438
2. Wraps the Google Services classpath with the `GoogleServicesEnabled` flag.
3.  Introduces the `GoogleServicesVersion` preference variable that allows users to override the default to use older or newer Google Services classpath. (Defaults to: `4.2.0`)
- `npm t`
- `cordova platform add`
- build with no `preference` attributes.
- build with preference `GoogleServicesEnabled` set to `true`
- build with preference `GoogleServicesEnabled` set to `true` and `GoogleServicesVersion` set to `4.1.0`
> feat: add google services support

- bin/templates/project/app/build.gradle
Change preference option names to increase better clarity by including more details.
Applied a pattern for all gradle related plugins:
`GradlePlugin<Plugin-Name><Action/Property> `
* `GradlePluginGoogleServicesEnabled`
* `GradlePluginGoogleServicesVersion`
- `npm t`
> chore: rename gradle plugin google services preference options

- framework/src/org/apache/cordova/BuildHelper.java
- framework/src/org/apache/cordova/CoreAndroid.java
Android
Resolving `BuildConfig` using android package name (`Context.getPackageName`) will only work when java and android package names are the same.
Android package name is effectively its `applicationId` which does not have to match java package name.
A common practice is to use different android package names for different built variants/flavours, ie:
```
debug {
applicationIdSuffix ".debug"
}
```
Now the applicationId (and android package name) might be something like `com.example.debug`, but `BuildConfig `will still resolve by `com.example.BuildConfig` instead of `com.example.debug.ClassName`
This pull request resolves issue #513.
Now using `java.lang.Class.getPackage()` instead of `android.content.Context.getPackageName()`
Tested with and without `applicationIdSuffix` with single …
> Use java package name for loading BuildConfig

- framework/cordova.gradle
Just minor code cleanup
- simplify `doFindLatestInstalledBuildTools`
- remove `getAvailableBuildTools`
- update com.g00fy2:versioncompare
- use string interpolation for error messages
`npm t`
> refactor: simplify doFindLatestInstalledBuildTools

- bin/clean_test.js
- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/cordova/lib/config/GradlePropertiesParser.js
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
- gulpfile.js
- package.json
- test/build.gradle
- test/wrapper.gradle
Android
Updates gradle version to the latest release (currently 6.1). It solves a few issue tickets that supposedly was caused after upgrading Android Studio.
Fixes #780 
Fixes #754 
Fixes #718 
Fixes #834 
Changed the desired gradle version from 4.10.3 to 6.1
I have tested using `npm test` and all tests passed. Note that if you have ran `npm test` before, you will need to remove the `/test/gradlew` file so the test project will download the new gradle version.
I have also tested by creating a brand new cordova app, and adding the `cordova-android` platform by using `cordova platform add https://github.com/breautek/cordova-android.git#gradle-5.x`
Then running the `cordova build android` command.
I'd also like to make a note that gradle 5.5.1 does currently produce a warning stating:
> …
> [MAJOR] Gradle upgrade from 4.10.3 to 6.x

- bin/templates/cordova/lib/check_reqs.js
- spec/unit/check_reqs.spec.js
Android
This PR fixes `cordova requirements android` to consider the desired target SDK as defined by the `android-targetSdkVersion` preference in the project's `config.xml`.
Fixes #846 
Currently, while `cordova-android` *can* use a higher target... it fails the `cordova requirements android` check if the hard-coded defined target is not installed on the system.
I've changed `check_reqs.js` `get_target` to do the following:
1. Get the default/minimum required target sdk, as defined by `cordova-android`
2. Check if `config.xml` exists in the repo.
3. If so, then attempt to read the `android-targetSdkVersion` preference.
3. 1. If read... check for validity
3. 1. 1. If valid, and is >= the default target sdk, then change the target to the preference value
3. 1. 2. If not valid, then …
> Fix: Cordova requirements consider the android-targetSdkVersion

- .ratignore
- README.md
Remove residual references of AppVeyor
Removed from RAT and README
No Testing Required
> chore: remove appveyor residual

- bin/lib/create.js
- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/check_reqs.js
- bin/templates/cordova/lib/device.js
- bin/templates/cordova/lib/emulator.js
- bin/templates/cordova/lib/log.js
- bin/templates/cordova/lib/retry.js
- bin/templates/cordova/lib/run.js
- bin/templates/cordova/version
fixes: #938
Bin files that contains the shebang interpreter fails when being rewired.
* Remove shebang from logical files that do not need it.
* Move version logic into `Api.js` and stop requiring the bin file
- `npm t`
- `cordova create`
- `cordova platform add android`
- `cordova run android`
- `cordova prepare android`
- Create platform though Platform-Centered workflow
> fix: test failure with shebang interpreter in rewired files

- README.md
Java 8 is required, not anything less, not anything greater. Java 1.8.x specifically is required by the android sdk.
> Docs: Updated README to reflect what Android requires more accurately

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- spec/unit/builders/ProjectBuilder.spec.js
Android
There was an issue when building app bundles where it did not obey flags. This was an error in the original implementation where arguments was only propagated to gradle if the package type was "apk". This PR corrects this mistake.
Closes #873 
Moved a line that pushes gradle arguments outside of the package type condition, as it is applicable 
to both package types.
Unit tests was added for both package types to ensure they both have args filled out as expected.
NPM test runs successfully, including 2 new tests that was added.
I've also ran `aapt` and `bundletool` to inspect the built files to ensure that the versionCode was as expected.
> fix: GH-873 App bundle builds to obey --versionCode arguments

- bin/templates/project/build.gradle
- bin/templates/project/legacy/build.gradle
- framework/build.gradle
- framework/src/org/apache/cordova/engine/SystemCookieManager.java
- framework/src/org/apache/cordova/engine/SystemWebChromeClient.java
- framework/src/org/apache/cordova/engine/SystemWebViewClient.java
- test/android/app/build.gradle
- test/androidx/app/build.gradle
Android
As was discussed on the mailing list, the plan is to raise the minimum supported API level to 22, dropping support for Android 4.4 and 5.0 for the next major `cordova-android` release.
This PR updates the `defaultMinSdkVersion` to 22. 
There are also a couple of places in the codebase where we have specific logic for older (i.e. KitKat) API-levels which are now no longer needed and can therefore be removed.
I also renamed the `needsKitKatContentUrlFix` function to just `needsContentUrlFix` as it is no longer KitKat specific.
And lastly, I did some minor whitespace fixups and removed an obsolete piece of commented out code.
I ran `npm run test` without issues and tested the changes in one of my own apps.
> Bump minSdkVersion to 22 and drop pre-Lollipop specific code

- framework/src/org/apache/cordova/engine/SystemWebChromeClient.java
Android
The chromium webview will print an informational log already,
we don't need to override the method to do what the webview will already.
Closes #914 
Simply removes the `onConsoleMessage` message override, since we don't do anything other than to print a logcat message out, which the super class already does, resulting in duplicate logcat prints.
Ran npm test and ensured all existing tests passes.
> fix: Removed redundent logcat print

- framework/src/org/apache/cordova/CordovaWebViewImpl.java
Android
This PR proposes a simple, quick, solution to overcome a problem with full screen mode that, when on and back button is pressed, the application is closed instead of exiting full screen. 
For more details see #822 and also https://bugs.chromium.org/p/chromium/issues/detail?id=999212
Fixes #822 
The custom view provided by WebKit on SystemWebChromeClients's `onShowCustomView` method is wrapped in a custom FrameLayout in order to be able to grab key events and redirect them into `SystemWebView`'s `dispatchKeyEvent`. 
Given that the custom view is the one with the focus, that's the one handling input, for this reason, we can hijack those key events and redirect them so that they end up closing the custom view because, as stated on the linked chromium bug …
> Prevent exit fullscreen mode from closing application 

- package.json
Use latest npm dependencies
Requires #953
**Bump Dev Dependencies**
* jasmine-spec-reporter@^5.0.1
* nyc@^15.0.1
* rewire@^5.0.0
**Bump Production Dependencies**
* android-versions@^1.5.0
* cordova-common@^4.0.0
* execa@^4.0.0
* fs-extra@^9.0.0
* nopt@^4.0.3
* which@^2.0.2
- `npm t`
> breaking(npm): bump packages

- bin/templates/cordova/lib/AndroidManifest.js
- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/cordova/lib/check_reqs.js
- bin/templates/cordova/lib/emulator.js
- bin/templates/cordova/lib/prepare.js
- package.json
- spec/e2e/plugin.spec.js
- spec/unit/AndroidManifest.spec.js
Bump ESLint dependency and apply auto fixes
Requires #953, #954
- `npm t`
> chore(eslint): bump eslint & apply fixes

- .npmignore
- Cleanup the npm package with `.npmignore`
- Add `.npmignore` file
- `npm t`
- Project
- `cordova create`
- `cordova platform add` with the cleanup npm package
- `cordova run android`
> chore(npm): add ignore list

- framework/build.gradle
Android
Upgrades the android gradle plugin from version 3.3.0 to 3.5.3. This is a prerequisite to other PRs. 
ran `npm test`
> feat: com.android.tools.build:gradle:3.5.3

- test/androidx/app/build.gradle
- test/androidx/build.gradle
- test/androidx/wrapper.gradle
Android
Fixes androidx test versions, who was still on gradle 4 and android gradle plugin 3.5.3, inconsistent with its `android` test sibling.
Upgrade gradle version pins
Ran `npm test`
> test: synced androidx gradle versions to the same version as the android test

- bin/templates/cordova/lib/check_reqs.js
- framework/cordova.gradle
- spec/unit/check_reqs.spec.js
Android
Fixes #949 which describes a functional issue
Fixes #670 which describes a cosmetic issue that is loosely related.
This PR depends on two other PRs: #959 #960 
This PR does the following:
- Makes ANDROID_SDK_ROOT the primary variable to look for the Android SDK location.
- Makes ANDROID_HOME the fallback variable, if ANDROID_SDK_ROOT is not present/valid.
~~Gradle updates:~~
~~Note that the following gradle updates were required, otherwise the android gradle plugin did not honour the ANDROID_SDK_ROOT variable.~~
- ~~Updates the framework's android studio's gradle plugin from version 3.3.0 to 3.5.3.
Not only this is required for android's gradle to obey ANDROID_SDK_ROOT, it is now in sync with the Android test project/~~
- ~~Updates the Androidx test project to use gralde plugin …
> fix: ANDROID_SDK_ROOT variable

- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/config/GradlePropertiesParser.js
- bin/templates/cordova/lib/prepare.js
- spec/unit/config/GradlePropertiesParser.spec.js
- spec/unit/prepare.spec.js
Android
Provides a `--jvmargs` flag to pass through JVM args to gradle. This is mostly useful for changing the `-Xmx` flag, allowing the JVM to use more memory on larger projects.
There was no feature request made, but it does closes https://github.com/apache/cordova-android/pull/945 ; a PR that changes the default memory size to 4096m.
I believe this is a better alternative as I believe it is better to keep the `-Xmx` as low as possible and for most users, our default value of 2048m is probably fine, but allows the flexibility for users to change the value based on their own unique needs. Additionally, this accepts any [JVM args](https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory), so not necessary limited to `-Xmx` flag.
The flag works on …
> Feature: JVM Args flag

- framework/build.gradle
- test/android/build.gradle
- test/androidx/build.gradle
Android
Upgrades android gradle plugin to 3.6.0.
afaik there are no issues that are dependant on this change, but this is usually considered a breaking change, so it would be great to be included in the 9.0.0 release.
Updated the framework and the two android test projects version pins.
ran `npm test`
> breaking: Bump android gradle plugin to 3.6.0

- bin/templates/cordova/lib/build.js
The timeout for detectArchitecture() is sometimes too low when devices are on wifi network connections and even sometimes over USB. The command can take up to 3 seconds to execute and return. Currently the timeout is set to 1000 ms and setting it to 5000 ms seems to be a good compromise.
Android
https://github.com/apache/cordova-android/issues/963
Increased the detectArchitecture() method timeout from 1000 ms to 5000 ms
Changing the timeout does not affect and unit tests.
> Increased detectArchitecture() timeout

- bin/templates/cordova/lib/emulator.js
- spec/unit/emulator.spec.js
Android
Fixes: #698 
Changes `wait_for_boot` from using `ps` shell command to check for `android.process.acore` to `getprop sys.boot_completed`
`android.process.acore` is a process that (despite it's name) is used for the `ContactsProvider`. The process is launched on boot, but will get killed after some amount of inactivity. When this happens, emulators that are opened for approximately 15 minutes or more will cause `cordova run android` to hang indefinitely.
Using `getprop sys.boot_completed` is a more reliable way to determine if the simulator has been booted.
A longer research comment I have posted on the issue ticket at https://github.com/apache/cordova-android/issues/698#issuecomment-632300908
Additionally one unit test has been updated to reflect this change.
I believe this is a …
> fix: wait_for_boot waiting forever

- bin/templates/project/app/build.gradle
(in the template)
Android
Discovered while working on Gradle update in PR #988
Note that `git grep -c ' $'` shows trailing spaces in a number of other files. I discovered something similar in cordova-ios, would like to go through the other repos if I get a chance someday.
remove trailing spaces from bin/templates/project/app/build.gradle
- `npm test`
- tested with `cordova-sqlite-storage` test app
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- ~~I've …
> cleanup: remove trailing spaces from app/build.gradle

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
- framework/build.gradle
- spec/fixtures/android_studio_project/build.gradle
- test/android/build.gradle
- test/android/wrapper.gradle
- test/androidx/build.gradle
- test/androidx/wrapper.gradle
Android
- Android Studio 4.0 recommended updating to multiple `build.gradle`
- Gradle 6.1.1 update seems to be required to build with Android Gradle plugin 4.0.0 update, may as well go with Gradle 6.5 update
I think it would be ideal if we could make this update before shipping the new major 9.0.0 release.
- update to use Gradle 6.5
- update the following `build.gradle` files as suggested by Android Studio 4.0:
- `bin/templates/project/app/build.gradle`
- `bin/templates/project/build.gradle`
- `framework/build.gradle`
Note that this proposal would effectively overwrite some or all changes from the following PRs:
- #962
- #792
/cc @erisu @breautek
- tested with command-line build from Cordova CLI
- tested with Android Studio 4.0
- ~~Commit is prefixed with `(platform)` if this change only …
> [major] feat: Gradle 6.5 & Android Gradle plugin 4.0.0 updates

- framework/src/org/apache/cordova/NativeToJsMessageQueue.java
__Updated__
Android
see #986 - I think this is needed to avoid crash with JSON memory issue in case of a large number of moderately-sized plugin response messages
_Note that this would affect the size of combined responses sent to the JavaScript and **not** the maximum size of any individual response message._
I hope we can consider this change for cordova-android 9.0.0 which should be coming in the near future.
- reduce the internal payload cutoff constant from 500 MB to 16 MB, as I had proposed in #986
- rename the payload cutoff constant to `COMBINED_RESPONSE_CUTOFF`
- update some comments
- cleanup: split if statements into multiple lines
note that this does **not** completely resolve the issues I raised in #986 due to the ugly warning messages still lurking
As I said in #986:
- …
> breaking: reduce combined response cutoff to 16 MB

- framework/src/org/apache/cordova/CordovaClientCertRequest.java
- framework/src/org/apache/cordova/CordovaHttpAuthHandler.java
- framework/src/org/apache/cordova/CordovaInterface.java
- framework/src/org/apache/cordova/CordovaPreferences.java
- framework/src/org/apache/cordova/CordovaResourceApi.java
- framework/src/org/apache/cordova/ICordovaClientCertRequest.java
- framework/src/org/apache/cordova/ICordovaHttpAuthHandler.java
- framework/src/org/apache/cordova/PluginResult.java
- framework/src/org/apache/cordova/engine/SystemWebViewClient.java
- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Android
see title
see title
✅ `npm test` in my work area - OK
✅ tried using in `cordova-sqlite-storage` test app - OK
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- ~~I've updated the documentation if necessary~~
> cleanup: remove trailing spaces from Java sources

- bin/templates/cordova/lib/android_sdk.js
- spec/unit/android_sdk.spec.js
android
Fixes #981 
If a plugin declares a `android-sdk` engine requirement such as `<engine name="android-sdk" version=">=26" />` the plugin may unexpectedly fail if the following conditions are met:
1. You have an appropriate SDK version installed (such as version `android-28`)
2. You have android preview SDK installed.
If the android preview SDK is installed, it was treated as the highest sdk version, even if it has no numerical value. This then led to errors such as:
```
Installing "cordova-plugin-local-notification" for android
Failed to install 'cordova-plugin-local-notification': TypeError: Invalid Version: android-R
at new SemVer (/home/norman/.nvm/versions/node/v14.2.0/lib/node_modules/cordova/node_modules/semver/semver.js:323:11)
at Range.test …
```
> fix: Plugin install fails when preview sdk is installed

- bin/templates/cordova/lib/prepare.js
android
fix: #984 
Adds a condition check and the android icons loop for dealing with adaptive icons. If `background` or `foreground` is missing, it skips it.
Ran `npm test`
> fix: support both adaptive and standard icons at the same time

- framework/src/org/apache/cordova/engine/SystemWebChromeClient.java
Accept multiple mime types on file input
Android
Accept multiple mime types when using file chooser
Replace: https://github.com/apache/cordova-android/pull/707
Fix: https://github.com/apache/cordova-android/issues/695
Tested on Android devices.
- [ x] I've run the tests to see all new and existing tests pass
- [ x] I added automated test coverage as appropriate for this change
- [ x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ x] I've updated the documentation if necessary
> Accept multiple mime types on file input

- bin/templates/cordova/lib/config/GradlePropertiesParser.js
* User plugins are most likely not ready to support AndroidX.
* Users are most likely not be aware of the AndroidX support roadmap and that this major would have been enabled by default but instead to be pushed back for next major.
- `npm t`
> chore: set AndroidX off by default

- spec/helper.js
`true` is not a valid value for the `displayStacktrace` option of `jasmine-spec-reporter`.
> test: fix missing stack traces in jasmine output

- package.json
- test/clean.js
This includes the following changes:
- move this developer-only script to test/ where it conceptually belongs
- this also prevents it from being distributed with this package
- fix paths for `android` and `androidx` variants
- make paths relative to the script, not to CWD
- use `removeSync` instead of `existsSync` and `existsSync`
- rename npm script to `clean:java-unit-tests` to clarify scope
> test(java): fix, improve and move clean script

- bin/templates/cordova/Api.js
- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/run.js
- spec/unit/Api.spec.js
- spec/unit/run.spec.js
This reduces dependence on the `builders` module and reduces repetition.
This also facilitates another WIP refactoring I am working on.
Create a single `ProjectBuilder` instance during `Api` construction and use that instance everywhere it is accessible.
Existing tests pass.
> refactor: save ProjectBuilder instance in Api instance

- bin/templates/cordova/lib/builders/ProjectBuilder.js
Android
A regression was made during the refactor of `shelljs` to `execa`. The current working directory was the cordova project root, which caused the gradle properties file in the android project folder to be ignored.
fixes #1011 
I've specified the cwd in the execa settings in every place that looked appropriate, to be the android project directory (`platforms/android`).
Ran `npm test`
Manually tested my fork.
Easiest way to test is by running `cordova build android`, wait until gradle starts... then run `ps -aux | grep 'Xmx'`
The expected output of the java processes should be something like `/usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xmx2048m`
> fix: gradle ignore properties

- spec/unit/pluginHandlers/common.spec.js
- test file setup was overly verbose
- teardown was faulty (exceptions in tests could lead to files being left behind)
- I wanted to add a regression test to the suite
- use `fs.outputFileSync` to create files and their parent dirs
- use `afterEach` to reliably clean up after tests
Affected unit tests still pass
> test(pluginHandlers/common): better setup & teardown

- bin/templates/cordova/lib/pluginHandlers.js
- package-lock.json
- package.json
- spec/unit/pluginHandlers/common.spec.js
The current check for _"Is path A inside path B?"_ relies solely on prefix checking. In general, that is not robust enough.
A real-world example where it fails, is when `Api.createPlatform` is called with a `destination` that is outside of `process.cwd()`. For example a temp dir during a test. This occurred when refactoring E2E tests.
This relies on proper test cleanup as implemented in #1013.
Use `is-path-inside` library.
- `Api.createPlatform` now works as expected
- added regression test
The new test calls `copyFile` with the same arguments as Test#006 and Test#007 with the sole difference that the project dir is relative to the current dir.
> fix(pluginHandlers): properly check if path is inside another

- bin/templates/cordova/lib/emulator.js
Improve maintainability by removing unused code.
Removes the functions `emulator.create_image` and `emulator.list_targets`
Tests still pass.
> chore: remove unused emulator.create_image and local dependencies

- .github/workflows/ci.yml
Adds Node 14.x to the CI matrix, which is the new current and will be the LTS later this year.
> ci: Added Node 14.x

- framework/src/org/apache/cordova/CordovaBridge.java
Android
Fixes #638
The issue is an older issue that pointed out that `SecureRandom` isn't actually secure on android devices pre 4.4. As it's been not supported for such time, it's safe to remove the `@suppressLint TruelyRandom`, which will provide us insurance that this method is not modified in an insecure manner in the future.
Ran `npm test`.
> refactor: Stop suppressing unnecessarily TruelyRandom lints

- package.json
See https://docs.npmjs.com/files/package.json#enginestrict
Related to https://github.com/apache/cordova/issues/55
> chore(pkg): remove deprecated no-op field "engineStrict"

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
- framework/build.gradle
- spec/fixtures/android_studio_project/build.gradle
- test/android/build.gradle
- test/android/wrapper.gradle
- test/androidx/build.gradle
- test/androidx/wrapper.gradle
Android
[To keep Android projects sync with latest Gradle versions and anything related to Gradle]
As Android Gradle plugin release notes https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
Related to Gradle version and Android Gradle Plugin.
Here what the latest versions:
Updates:
- Gradle version to 6.6.1
- Android Gradle Plugin version to 4.0.1
- com.jfrog.bintray.gradle to 1.8.5
> [Frequent Updates] Gradle 6.6.1 & Android Gradle Plugin 4.0.1 & com.jfrog.bintray.gradle 1.8.5

- bin/templates/cordova/lib/prepare.js
The pattern contained an additional plus that slipped in during the refactoring done in #842. See [the diff][1] for details.
It's unlikely that this bug actually affects anyone.
[1]: https://github.com/apache/cordova-android/pull/842/commits/09e8248d1f0bbf5c833765e71dbf2343c38cc6bf#diff-26c51bfaa44eff1e46fd61ec3225ec13L640-R650
> fix(prepare): fix pattern used to collect image resources

- bin/templates/cordova/lib/prepare.js
- bin/templates/cordova/lib/utils.js
- package-lock.json
- package.json
Reduce amount of code to maintain.
- Inlined `utils.grep` at only point of usage
- Replaced `utils.scanDirectory` with `fast-glob`
Existing tests pass
> refactor(utils): reduce number of utils

- spec/unit/Api.spec.js
- spec/unit/check_reqs.spec.js
Some tests were not order independent
Fixed unit tests to be independent of execution order. See commits.
Tests pass for various random orders
> test: fix unit test failures for certain random orders

- bin/templates/cordova/lib/build.js
- bin/templates/cordova/lib/device.js
- spec/unit/device.spec.js
Closes #1098
This basically reverts 66fa12a.
Unit tests pass & works for me on Linux
> refactor: do not kill adb on UNIX-like systems

- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Fixes SDK 30 related issues
Loading `file://` resources is failing in SDK API 30 because the `setAllowFileAccess` is now defaulted to `false`.
To keep existing behavior, we should set this to `true`, but in future releases we should default it to `false` and have the files loaded not though file. 
With the camera plugin, took a photo and loaded the `FILE_URI` in `<img>` tag.
> fix(android): allow file access for existing behavior

- bin/templates/cordova/lib/Adb.js
- bin/templates/cordova/lib/emulator.js
- spec/unit/emulator.spec.js
`emulator.install` contains a copy of the code of `Adb.install` just to be able to pass custom options to `execa`.
This change removes that duplicated code in favor of a new option in `Adb.install` that allows to pass through options to `execa`.
Unit tests.
> refactor: remove copied Adb.install from emulator.install

- bin/templates/cordova/lib/check_reqs.js
- spec/unit/check_reqs.spec.js
I was thrown off by [the regex introduced in #842](https://github.com/apache/cordova-android/pull/842/files#diff-0d1afa0d5c88bdb18fbc6ab9ef7fc4bbe10f7047d387bb2964932dbb6eb8c4b7R47) to match JDK folders. While it matches what we want, it is somehow misleading ("does the dir start with an arbitrary long sequence of `jdk` strings followed by any single character?").
- use `fast-glob` to change the implementation back to the more straightforward "give me all directories that start with `jdk`"
- add a unit test for that feature
- remove a useless `if`
- use `ProgramFiles(x86)` env var to cover all bases
New unit test passes
> refactor(check_reqs): cleanup default Java location detection on Windows

- bin/templates/cordova/lib/Adb.js
- bin/templates/cordova/lib/device.js
- bin/templates/cordova/lib/emulator.js
- spec/unit/Adb.spec.js
- spec/unit/device.spec.js
- spec/unit/emulator.spec.js
Previously `Adb.devices` returned _either_ emulators _or_ devices. This change allows one to get a list of devices _and_ emulators in one go. This enables refactors that improve performance & stability.
This PR is a dependency of #1101.
- `Adb.devices` now returns the IDs of _all_ targets in the state `device`
- `device.list` and `emulator.list_started` implement the respective filtering (in a simpler manner than `Adb.devices` did)
- Adapted the unit tests accordingly
- Automated unit tests
- Manual testing
> feat(Adb): list devices _and_ emulators in one go

- test/android/app/src/androidTest/java/org/apache/cordova/unittests/BackButtonMultipageTest.java
- test/androidx/app/src/androidTest/java/org/apache/cordova/unittests/BackButtonMultipageTest.java
This is a recreation of https://github.com/apache/cordova-android/pull/1038
See https://github.com/apache/cordova-android/pull/1038#issuecomment-731494936 for why a new PR was created.
This PR contains the original commit authored by @leofernandesmo
I've added a second commit that applies a [review suggestion](https://github.com/apache/cordova-android/pull/1038#pullrequestreview-502734637) and also mimic the changes in the androidx commit for consistency.
Android
Test code may contain undesirable duplication. Solutions are similar to those for normal code duplication as described by Fowler. 
Removing duplication helps maintainability of the test.
I applied extract method and defined constants for duplicate strings.
Ran npm test
> test(java): remove duplicate code in BackButtonMultipageTest

- bin/templates/cordova/lib/prepare.js
I broke `mapImageResources` when refactoring it to use globbing in #1085. The problem is, that `fast-glob` will only match files by default while we are looking for directories here.
Pass `onlyDirectories` option to `fast-glob`.
> fix(prepare): mapImageResources always returning []

- bin/templates/cordova/lib/builders/ProjectBuilder.js
Android
Building bundles broke at some point between 9.0.0 and nightly.
Fixes https://github.com/apache/cordova-android/issues/1151
When building bundles, the `arch` setting is not supplied. This is provided through an options parameter, but you cannot deconstruct a object that doesn't exists. Therefore, I made the options parameter default to `{}`. The `arch` option remains optional.
Ran `npm test`.
> fix: optional arch parameter

- bin/templates/cordova/lib/check_reqs.js
- bin/templates/cordova/lib/env/java.js
- bin/templates/cordova/lib/utils.js
- package-lock.json
- package.json
- spec/unit/check_reqs.spec.js
- spec/unit/java.spec.js
Android
Prerequisite PR for https://github.com/apache/cordova-android/issues/1060
This PR abstracts the Java checks and java version retrieval so that it can be reused.
Created a new Java class with static methods that provides an API to get the version. It also contains the code that finds the java executable that used to live inside `check_reqs`.
`Java.js` is contains 100% line coverage, which is an upgrade from when the code lived in `check_reqs`.
`npm test`
> refactor: java checks / get java version

- bin/lib/create.js
- spec/unit/create.spec.js
- Android
Closes #1172 
Tried locally but couldn't run (probably I have to read it more carefully).
> feat(android-studio): display app name as project name

- framework/src/org/apache/cordova/PluginManager.java
Fix for #924 
Android
ConcurrentModificationException occurs when starting app, and sometimes randomly in app usage
Use `Collection.synchronizedMap` and ensure all access is sync by wrap all usage of the collection with `synchronized` keyword
Used for a few months in production now without any issues
> fix: Concurrent Modification Exception

- framework/src/org/apache/cordova/CordovaWebViewImpl.java
Android 
See issue and sample MVP/Videos in : https://github.com/apache/cordova-android/issues/1002
Fixes #1002 
Added null pointer checks around ```cordova.getActivity()```, to check if the activity hosting Cordova is still alive.
Updated MVP (see issue #1002 ) locally with these changes (also updated gradle but is not pushed in this PR).
> fix: add not null checks to prevent running on destroyed activity

- framework/src/org/apache/cordova/PluginManager.java
Android
Fix #924 
We have a project with 31 plugins installed, in some devices like Huawei p30( or emulator Pixel_3-x86_64 android R)  fail starting the app 4 of 10 times.
Showing the _ConcurrentModificationException_ error from the **webView.postMessage("splashscreen", "hide");** of the **SplashScreen.java**
Tracking the #924 thread I found a code to avoid the error using [.synchronizedMap](https://github.com/breautek/cordova-android/commit/bfda452a09ba26412e0f527f6af1957379d89453). This was not enough the app still crash sometimes.
Then testing using the .forEach instead of the **for (CordovaPlugin plugin : this.pluginMap.values())**  works. No more _ConcurrentModificationException_ were thrown.
A counterpoint is that .forEach is not available prior android 6 and a check version is …
> fix: Avoid Crash Report: ConcurrentModificationException

- bin/templates/project/app/build.gradle
Android
Google Services Gradle Plugin @4.3.5
> feat: upgrade Google Services Gradle Plugin google-services@4.3.5

- framework/src/org/apache/cordova/CordovaWebViewImpl.java
Make sure to call dispatchKeyEvent from base class in WrapperView, if the event hasn't been handled by the engine.
Fixes #1156
> fix: restore key event handlers when DOM element is fullscreen

- spec/unit/check_reqs.spec.js
- spec/unit/prepare.spec.js
`expectAsync` need `await`. With out await, tests can fail.
- Added `await` & `async` where needed.
- `npm t`
> fix: unit-test failure

- bin/templates/cordova/lib/check_reqs.js
- spec/unit/check_reqs.spec.js
Android
https://github.com/apache/cordova-android/pull/1130#discussion_r563597125 decision caused a regression in the `cordova requirements` command, it turns out, `check_java` method **must** return a value.
Fixes https://github.com/apache/cordova-android/issues/1180
Return the java version in `check_java`
Added a unit test to ensure `check_java` returns a value and ensured all unit tests passes.
> fix(regression): Cannot read version of undefined caused by Java refactor

- bin/lib/create.js
Build fails because the `repositories.gradle` files are not copied into the project during the initial project creation.
> fix: copy repositories.gradle to project on create

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/project/app/build.gradle
- test/android/wrapper.gradle
- test/androidx/wrapper.gradle
Reverts apache/cordova-android#1174
Sorry, it seems some people do not trust that this follows semver and feels it may not fit a minor release.
We will revert this PR and would like it resubmitted for the major release.
> Revert "feat: upgrade gradle@6.8.3"

- bin/templates/project/app/build.gradle
Reverts apache/cordova-android#1177
Sorry, it seems some people do not trust that this follows semver and feels it may not fit a minor release.
We will revert this PR and would like it resubmitted for the major release.
> Revert "feat: upgrade Google Services Gradle Plugin google-services@4.3.5"

- framework/src/org/apache/cordova/CordovaResourceApi.java
This improves the energy efficiency of cordova-android by applying the Reduce Size Energy Pattern for mobile applications.
The energy pattern was applied in CordovaResourceApi.java. The general idea is when receiving data from an URLConnection or subclasses, if possible, receive the data compressed by GZIP scheme. In this specific case, when receiving data from the conn variable, request for the data to be compressed.
> feat: support gzip encoding requests & use GZIPInputStream

- bin/templates/project/build.gradle
- framework/project.properties
- spec/fixtures/android_studio_project/app/build.gradle
- spec/unit/check_reqs.spec.js
- test/android/app/build.gradle
- test/androidx/app/build.gradle
Bump default target SDK: **30**
Bump build-tools: **30.0.3**
- `npm t`
> feat: target sdk 30 w/ build-tool 30.0.3

- bin/templates/project/app/build.gradle
- framework/build.gradle
* Reintroduces changes that were reverted to not cause issues with 9.1.0 release.
* Changes were cherry-picked to retain original author.
* Original PR Work:
* https://github.com/apache/cordova-android/pull/1177
* Upgrades Google Services Gradle Plugin to 4.3.5
**PR is based off PR #1198 and should be rebased after merged.**
> feat!: upgrade Google Services Gradle Plugin@4.3.5

- framework/build.gradle
* Reintroduces changes that were reverted to not cause issues with 9.1.0 release.
* Changes were already cherry-picked in a previous PR but to retain original author I added him as Co-Author.
* Original PR Work:
* https://github.com/apache/cordova-android/pull/1079
* Upgrades JFrog Bintray Gradle Plugin to 1.8.5
Even though this plugin maybe removed in the 10.0.0 release, the goal of this PR is to reintroduce the original contribution as much as possible.
**PR is based off PR #1200 and should be rebased after merged.**
> feat!: upgrade jfrog gradle-bintray-plugin@1.8.5

- framework/src/org/apache/cordova/CordovaPlugin.java
- framework/src/org/apache/cordova/PermissionHelper.java
Android
Closes #592 
Deprecates `onRequestPermissionResult` for `onRequestPermissionsResult` for consistency with the [Android API](https://developer.android.com/reference/androidx/core/app/ActivityCompat.OnRequestPermissionsResultCallback)
This change is not breaking, but will signal a breaking change some time in the future.
Ran `npm test`
Also did a live manual test with the geolocation plugin, both with it using the deprecated method and the new method.
> feat: Deprecated onRequestPermissionResult in favour for onRequestPermissionsResult for consistency

- bin/templates/project/app/build.gradle
- framework/cordova.gradle
Android
Closes #1021 
Removes the gradle keystore password prompt implementation. It was buggy and never worked well for a significant period of time, due to how gradle daemonizes its processes. 
**This is a breaking change**
Intended for the v10 milestone release.
`npm test` and manual testing with `build.json` file.
> breaking: remove keystore password prompt

- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Android
The App Cache API will soon be removed: https://web.dev/appcache-removal/
The app cache methods for  `WebSettings` are another thing that get deprecated for API level 30: https://developer.android.com/reference/android/webkit/WebSettings#setAppCacheEnabled(boolean)
The app cache web API is considered deprecated and will get removed from Chrome/the Android webview around April 2021. Service workers are considered an alternative.
Unit tests
> breaking: remove deprecated AppCache settings

- bin/templates/project/build.gradle
- test/android/build.gradle
> feat!: upgrade kotlin@1.4.32

- spec/unit/AndroidManifest.spec.js
Update `AndroidManifest.spec.js` based on comment from this PR: https://github.com/apache/cordova-android/pull/1052#pullrequestreview-636784515
Changed `Theme.DeviceDefault.NoActionBar` to `Theme.AppCompat.NoActionBar` to match changes from PR https://github.com/apache/cordova-android/pull/1052
> test(AndroidManifest): update theme to Theme.AppCompat.NoActionBar

- bin/templates/cordova/lib/prepare.js
- bin/templates/project/app/build.gradle
- bin/templates/project/build.gradle
- framework/build.gradle
Allow the AndroidX AppCompat library version to be configurable.
Added a `config.xml` preference to allow users to override the default version at their own risk.
**Example Config:**
```xml
<platform name="android">
<preference name="AndroidXAppCompatVersion" value="1.3.0-rc01" />
</platform>
```
- npm t
- `cordova build android` with no change
- `cordova build android` with changes using the example config above that sets the version to `1.3.0-rc01`
> feat: allow appcompat version to be configurable

- framework/src/org/apache/cordova/PluginEntry.java
Android
resolves https://github.com/apache/cordova-android/issues/1164
This will allow to specify already instantiated PluginEntries with `onload = false`. 
Which will stop Cordova from initialising them multiple time and fix issue on AGP 4.1.2 that enables all asserts in debug 
Is setting onLoad false valid option here?
have a look at test exposing issue:
https://github.com/jblejder/cordova-android/pull/1
> feat: overload PluginEntry constructor to set onload property

- .github/workflows/ci.yml
Node 16 has been released, so time to start updating our CIs :grin: 
Progresses https://github.com/apache/cordova/issues/286
> ci: Add Node16 to CI matrix

- framework/src/org/apache/cordova/ConfigXmlParser.java
- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Android
As we discussed on the list we might need a fallback for the new changes in #1137 
With this PR you can fall back to using files instead of https://localhost with this preference:
`
<preference name="AndroidInsecureFileModeEnabled" value="true" />
`
Documentation: https://github.com/apache/cordova-docs/pull/1172
Manual
> feat: add backwards compatibility mode for WebViewAssetLoader

- bin/templates/cordova/lib/prepare.js
We copy default splash screens to the platform folder during platform creation. But then we do not delete them when the user uses no splash screens at all. This causes #1226 and what is described in #689.
Fixes #1226
The new implementation does not return early when updating splashes and none are defined. Instead, we let the cleanup map we create initially take care of deleting all unused splash screens. This also deletes the default splashes during the first prepare after platform creation.
Manual testing on a default app.
A regression test would be great but I'm on a tight schedule. Feel free to add one if you feel like it.
> fix(prepare): delete splash screens if none are used

- bin/templates/cordova/lib/env/java.js
- spec/unit/check_reqs.spec.js
Android
Fixes getting the java version from the `javac -version` output on macOS devices when custom `_JAVA_OPTIONS` are set. A detailed description of the issue can be found im my comment [here](https://github.com/apache/cordova-android/pull/1130#issuecomment-824749304).
Fixes https://github.com/apache/cordova-android/issues/1203
Use a regex to get just the version string from the `javac` output. Fixes #1130.
Previously `semver.coerce()` would get a wrong version from a string like the following:
```js
Picked up _JAVA_OPTIONS: -Xms1024M -Xmx2048M\njavac 1.8.0_271
```
With the change in this PR, the following regex is used to get the version string (`1.8.0`) from the output:
```js
/javac\s+([\d.]+)/i
```
I also tried removing `_JAVA_OPTIONS` from the version check by adding `env: {}, …
> fix(requirements check): use regex to get java version from javac output

- bin/templates/cordova/lib/env/java.js
- spec/unit/java.spec.js
Android
It's been a requested feature (not formally, but in variety of bug tickets of people trying to use java >8) because often times, we are stuck on using older Java versions
due to the Android SDK. This will make it easier for users to have multiple java versions installed.
If `CORDOVA_JAVA_HOME` is present, it will override `JAVA_HOME` environment variable for the execution context of Cordova.
Unit test added. All existing tests passes. Manual testing.
> feat: CORDOVA_JAVA_HOME env variable

- bin/templates/cordova/lib/env/java.js
- spec/unit/check_reqs.spec.js
- spec/unit/java.spec.js
This PR basically fixes up the changes from #1220. I was too busy to point out the problems before it was merged.
- improve and extend tests
- minor code improvements
The automated test suite passes
> refactor(env/java): improve tests and implementation

- bin/templates/cordova/lib/plugin-build.gradle
- bin/templates/project/app/repositories.gradle
- bin/templates/project/repositories.gradle
- framework/build.gradle
- framework/cordova.gradle
- framework/repositories.gradle
- spec/fixtures/android_studio_project/build.gradle
- test/androidx/app/build.gradle
- test/androidx/build.gradle
- Remove JCenter usage
- Remove Bintray usage
- Replace & Upgrade `com.g00fy2:versioncompare:1.3.4` with `io.github.g00fy2:versioncompare:1.4.1`
- Update all `repositories` definitions with:
```
repositories {
google()
mavenCentral()
}
```
- `npm t`
> breaking: drop jcenter/bintray & update dependencies

- framework/build.gradle
- framework/gradle.properties
- Drop `.github.dcendents:android-maven-gradle-plugin` which has been abandonded because maven-publish-plugin is supported by the Android Gradle Plugin 3.6.0 and higher
- Update the publishing definition to support publishing to maven
- Fixed the `gradle build` failure due to missing `useAndroidX` flag. The build is needed to create an `aar` release artifact that is bundled with the publish.
This PR requires #1251 to be merged in first.
You can see commit: https://github.com/apache/cordova-android/commit/2338bc6975fe592922f2070767be011f6b2aab13
If you want to see only the changes of this PR.
-  [x] `npm t`
-  [ ] Publishing package has not been tested yet.
> feat!: drop abandoned com.github.dcendents:android-maven-gradle-plugin

- spec/unit/prepare.spec.js
Just a minor test refactor to eliminate some duplicate code.
> tests(prepare): factor out common vars

- bin/templates/cordova/lib/builders/ProjectBuilder.js
- bin/templates/cordova/lib/check_reqs.js
- spec/unit/builders/ProjectBuilder.spec.js
This refactor removes a strange optional parameter from `check_reqs.check_android_target` in favor of having the sole user of that parameter handle the related logic itself.
> refactor(check_reqs): drop originalError param from check_android_target

- bin/templates/cordova/lib/prepare.js
- bin/templates/project/app/build.gradle
- framework/cordova.gradle
Allow `androidx.webkit` version overrides.
~~Forked of #1253. Requires parent PR merged in first.~~
- `npm t`
- build
- changing of versions
> feat: allow webkit version override

- spec/unit/check_reqs.spec.js
Should have been part of #1212
> test(check_reqs): do not hardcode DEFAULT_TARGET_API

- framework/cdv-gradle-config-defaults.json
- spec/fixtures/android_studio_project/gradle/wrapper/gradle-wrapper.properties
Bump Gradle to `7.1.1`. Using the new centralized configuration defaults.
Also updated test fixtures.
After some discussion and seeing that Gradle's website declares that they have tested with the current released AGP means there most likely wont be any issues in upgrading this, eventhough Google Android docs does not define it in the supported range.
- `npm t`
> feat!: bump gradle@7.1.1

- framework/src/org/apache/cordova/CordovaActivity.java
Fix missing super call error for the `onRequestPermissionsResult` override.
- `npm t`
> fix: missing super.onRequestPermissionsResult error (MissingSuperCall)

- bin/templates/cordova/lib/run.js
- spec/unit/run.spec.js
Refactoring that improves code quality of `run.run` and prepares the stage for other changes.
See commit messages. Slightest change in behavior during errors due to the first two commits.
Automated tests still pass
> refactor(run)!: cleanup run method

- bin/templates/cordova/lib/emulator.js
- bin/templates/cordova/lib/run.js
- bin/templates/cordova/lib/target.js
- spec/unit/emulator.spec.js
- spec/unit/run.spec.js
- spec/unit/target.spec.js
This reduces usage of `check_reqs.get_target` since that function only considers `config.xml` to find the target SDK and moreover relies on the script location to find `config.xml` (which has to change if we want to run the script from node_modules; also see #1265).
When looking for the best emulator image to run an APK on, the target SDK of that APK is determined by running `apkanalyzer manifest target-sdk`.
`apkanalyzer` is part of the Android SDK Tools since Revision 26.1.1 (September 2017).
- ran unit tests
- manually tested that the correct SDK is inferred from the built APK  during `cordova run`
> refactor: use target SDK of built APK to determine best emulator

- bin/templates/cordova/lib/build.js
This PR changes the default package type of the release builds to be `aab` (Android App Bundle). In August, AAB format is required for all new apps.
https://developer.android.com/distribute/play-policies#RequirementForNewApps
Exisiting apps can continue to release APK packages till November. To continue to build release APK, append the `--buildType=apk` flag to the build command.
- `npm t`
- Android build with command line
> feat!: release build defaults to aab package type

- lib/build.js
- package-lock.json
- package.json
Android, ios, Browser
I struggeling with home path every time changing build computer or transfer code to my teammate computer. the `build.json` config does not find home path on window with "command line" or "power shell". there is no tutorial about this. I have to go to build file to know that there is `~` equivalent with `$HOME` and `%HOMEPATH%` on window.
I think it is feature?
> fix(build): support tilde expansion on windows

- lib/Api.js
Have `Api.version` return the version from `package.json`, reducing the need for `coho` usage. There are still other places where the version is hardcoded, but that's beyond the scope of this PR.
> refactor(Api)!: use version from package.json

- framework/src/org/apache/cordova/CordovaWebViewImpl.java
Android
fixes: #1206
Request the focus if you exited from a custom view (like video fullscreen)
run `npm run test`
check result in android 9.1.0 on live app
> fix: request focus after custom view hided

- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Remove this setting once Cordova drops support for API Level 26.
> This method was deprecated in API level 26.
> In Android O and afterwards, this function does not have any effect, the form data will be saved to platform's autofill service if applicable.
> This method was deprecated in API level 18.
> Saving passwords in WebView will not be supported in future versions.
> This method was deprecated in API level 19.
> Database paths are managed by the implementation and calling this method will have no effect.
Remove this setting once Cordova drops support for API Level 24.
> This method was deprecated in API level 24.
> Geolocation database are managed by the implementation and calling this method will have no effect.
- `npm t`
> cleanup!: remove deprecated settings & add todo comments

- lib/config/GradlePropertiesParser.js
- Remove the forced default `org.gradle.daemon` setting.
- Per [Gradle Docs](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon):
> The Gradle Daemon is enabled by default, and we recommend always enabling it. You can disable the long-lived Gradle daemon via the --no-daemon command-line option, or by adding org.gradle.daemon=false to your gradle.properties file.
Since the `Gradle Daemon` is enabled by default, this default setting value is no longer needed.
Changes were cherry-picked from https://github.com/apache/cordova-android/pull/983.
This PR is based on the users master branch and is out-dated. To avoid rebasing his PR, I decided to create a new PR.
closes: #983
fixes: #982
- `npm t`
> fix: remove forced default gradle.daemon setting

- framework/src/org/apache/cordova/AllowListPlugin.java
Android
Addresses issues in #1217 
Closes #1217
With the introduction of the WebViewAssetloader #1137 and the Allow List Plugin #1138 we need to add the origin / href the app is running to the allowlist.
Create a blank new app with one plugin
```
cordova create test
cd test
cordova platform add https://github.com/apache/cordova-android#webviewassetloader-allowlist
cordova plugin add cordova-plugin-file
cordova run android
```
These steps will produce the hello world cordova app that should show "deviceready" with this pr. See issue.
> fix: add WebViewAssetloader to default allow list

- .github/workflows/ci.yml
- package.json
* Drop Node 10 Support from GH Actions Workflow
* Bump required Node engine to `>= 12.0.0`
Node 10 has been deprecated and no longer supported by the nodejs team.
Other packages has dropped node 10 and require node 12 and up.
- `npm t`
> chore!: drop node 10 support

- lib/getASPath.bat
Add missing Apache license header to getASPath.bat
> fix: add missing apache-license header to getASPath.bat

- README.md
Correct README requirements section
- n/a
> chore: update readme requirements

- templates/project/app/build.gradle
fixes: #1284
Build failure when Google Services Gradle Plugin is enabled. It fails because the version checking is calling a variable that was refactored and forgotten.
Changed old variable name `gradlePluginGoogleServicesVersion` to new variable name `cordovaConfig.GRADLE_PLUGIN_GOOGLE_SERVICES_VERSION`
- `npm t`
> fix: Google Services Gradle Plugin version check failure

- RELEASENOTES.md
Add missing old release notes.
resolves: #639 
Cherry-picked the missing release notes to main branch.
> fix: add missing release notes

- framework/src/org/apache/cordova/CordovaWebView.java
- package-lock.json
- package.json
Prepare for minor release `10.1.0`
Bump version in:
- package.json
- package-lock.json
- CordovaWebView.java
- `npm t`
> chore: bump version 10.1.0-dev

- framework/src/org/apache/cordova/ConfigXmlParser.java
fixes: #1296
fixes: #1289
fixes: #1299
`setStartUrl` was being called during the parsing of the `config.xml`. This should not be called until after the parsing has been completed. The reason why this was an issue is because `setStartUrl` was called when the `content` tag was being parsed. Some or all `preference` tags may not have been already loaded, so therefore we do not have the information to best determin what the start url should be.
This PR moves the `setStartUrl` in side the `getLaunchUrl`. The first call of `getLaunchUrl` will trigger the `setStartUrl` method. Any calls there after will return immediately the launchUrl as it will be saved from the first call.
With the changes described above, it resolved the reported issue in #1289.
Additionally, this PR allows users to set the …
> feat: support http w/ content src fix

- framework/build.gradle
- templates/project/app/build.gradle
- templates/project/build.gradle
Not all subprojects will have the `repositories.gradle` so therefore trying to apply `repositories.gradle` will fail.
This PR updates the logic to check if the `repositories.gradle` exists and if it does not, fallback and use the `repositories.gradle` that is in the project root directory.
- `npm t`
- `cordova build android` with a plugin that has a subproject.
> fix: fall back to project root repositories.gradle

- test/androidx/app/src/androidTest/java/org/apache/cordova/unittests/BackButtonMultipageTest.java
android
Fix the issue of `BackButtonMultipageTest`.
Adding `throws Throwable` in the `assertPageSample` methods
in order to fix the test error.
Do 
```
% npm run java-tests
```
in my local environment (mac).
> fix: backbutton test code

- README.md
Android
Dev and test doc not up to date.
Split from PR #1213.
(also see similar PR for cordova-ios apache/cordova-ios#1133)
Remove deprecated parts and reuse some from cordova-ios Readme.
.
> doc: update README about development & testing

- lib/builders/ProjectBuilder.js
- lib/create.js
- lib/prepare.js
- spec/unit/create.spec.js
Android
fixes #1209
(Android Studio resets project name on Gradle reload)
Add `rootProject.name = "Hello World"` inside **settings.gradle** at root.
Remove _.idea/.name_ file previously added with #1173 and [v9.1.0](https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md#910-apr-09-2021)
`npm test` success + project creation, open and run from IDE into emulator
Fine on 10.0.0-dev and same for 9.2.0-dev 👍 (would be nice to backport this into a 9.x fix release)
> fix: display project name in Android Studio

- lib/create.js
- spec/unit/create.spec.js
Android
Mixed default values for `create` between cli doc, cordova-android and cordova-ios.
And wrong project name if with spaces and accents:
fixes #1210
Package ids were mostly correct but not all, and same for project name. Suggested proper defaults:
- **id** / package name: `io.cordova.helloCordova`
- **name** / project name: `Hello Cordova`
See linked PRs: apache/cordova-cli#554, apache/cordova-ios#1100
And
- Fix #1210: project name not transformed anymore (was replacing non-word characters with underscores), because there is no known limitation with it, project creation and all still work fine, and cordova-ios does it the same way
- small update on main Readme to update/add details for use and test
_(see each commit for detail on my steps)_
`npm test` success + project creation, …
> feat: unify `create` default values & stop project name transform

- framework/src/org/apache/cordova/AllowListPlugin.java
- framework/src/org/apache/cordova/PluginManager.java
fixes: #1328
fixes: https://github.com/apache/cordova-plugin-device/issues/118
Update how the PluginManager handles the default policy.
* If `AndroidInsecureFileModeEnabled` is `true`, then the default policy is `file://`
* If `AndroidInsecureFileModeEnabled` is `false`, then the default policy is the combination of the `scheme` & `hostname`.
* The default scheme is: `https`
* The default hostname is: `localhost`
* If the user changes any of these values, it will be used.
* Creating Project
* Adding Platform
* Adding Device Plugin
* Changing `scheme` to `http`
* Changing `hostname` to `apache.org`
* Setting `AndroidInsecureFileModeEnabled` to `true`
I also tested a solution that added the fix to the `AllowListPlugin` class. https://github.com/apache/cordova-android/commit/fa5b228bb9cefca36 …
> fix(PluginManager): AllowBridgeAccess default policy to handle scheme & hostname

- framework/src/org/apache/cordova/AllowListPlugin.java
fixes: https://github.com/apache/cordova-android/issues/1322
`shouldAllowRequest` will throw an exception for all URLS that are not in the navigation allowed list.  This change safely tests the result of `shouldAllowNavigation`, avoiding the exception and allowing for the execution to continue to see if the URL is in the request allowed list.
Incorporating this change into our project successfully allows expected network requests that previously were allowed with the whitelist plugin.
> fix(AllowListPlugin): Safely handle default allow navigation policy in allow request

- framework/src/org/apache/cordova/PluginManager.java
Allow Navigation should also handle the default policy for scheme & hostname 
- `npm t`
- `cordova build`
- `cordova run`
> fix(PluginManager): AllowNavigation default policy to handle scheme & hostname

- lib/create.js
- lib/utils.js
- spec/unit/create.spec.js
Android
Error on `cordova platform add` when the Cordova app name contains the character `&`. The issue occurs when parsing the `strings.xml` file. The issue was introduced on cordova-android 10.1.0
Fixes https://github.com/apache/cordova-android/issues/1380
Simply replaces the `&` characters in the project name (if present) by an `_`. 
`npm test` and project creation successful
> fix: escape strings.xml app name

- framework/cordova.gradle
Android
Solves confusion as the current error message suggest they can install any newer version when that is often not the case.
Fixes #1391 
Removes text such as "or higher" / "or later" which suggest that the user can install any version later. Instead of attempting to explain that they need a specific major version, I reworded the text to suggest/recommend installing the default build tools version in which Cordova is tested against. Advanced users can still install alternate versions if they know what they are doing and the risks involved.
Ran npm test and manually tested by uninstalling build tools and trying to build.
Note: npm test will fail due to the lack of build tools version installed.
> fix(GH-1391): Reword minimum build tools version error message

- lib/env/java.js
Linux and Windows
Starting with Java 9 the JRE and JDK no longer include `tools.jar` as described in [JEP 220](https://openjdk.java.net/jeps/220). As a result the `check_java` function is unable to detect a Java 11 installation unless the `JAVA_HOME` environment variable is set manually:
https://github.com/apache/cordova-android/blob/6d3ce211dd813cc39517a4173068168f7fe2b95e/lib/env/java.js#L101-L102
The check for `tools.jar` appears to have been added in commit 7133576fe9ca8e8a3c91938eba524a843ccf8365.
This change instead checks for the presence of `${maybeJavaHome}/bin/java` or `${maybeJavaHome}/bin/java.exe`. This is similar to the checks performed by [`gradlew`](https://github.com/gradle/gradle/blob/master/gradlew#L126-L128) and …
> fix: detect JAVA_HOME with Java 11

- package-lock.json
Satisfy npm audit for the following issues:
ansi-regex  4.0.0 - 4.1.0 || 5.0.0
Severity: moderate
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/ansi-regex
node_modules/strip-ansi/node_modules/ansi-regex
minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist
plist  <=3.0.4
Severity: critical
Prototype pollution in Plist - https://github.com/advisories/GHSA-4cpg-3vgw-4877
Depends on vulnerable versions of xmldom
fix available via `npm audit fix` …
> chore: update package-lock to satisfy npm audit

- .github/workflows/ci.yml
- package.json
Android
[Node LTS Support](https://nodejs.org/en/about/releases/) is coming to an end April 2022. So it's a good time to drop support for Node 12 for our next major release.
Removed Node 12 from our test matrix, and upgraded our package Node engines.
Ran npm test
> chore!: Drop Node 12 support

- lib/Adb.js
- lib/AndroidManifest.js
- lib/AndroidProject.js
- lib/Api.js
- lib/android_sdk.js
- lib/build.js
- lib/builders/ProjectBuilder.js
- lib/check_reqs.js
- lib/create.js
- lib/emulator.js
- lib/env/java.js
- lib/pluginHandlers.js
- lib/prepare.js
- lib/retry.js
- lib/run.js
- package-lock.json
- package.json
- spec/unit/Api.spec.js
- spec/unit/check_reqs.spec.js
- spec/unit/create.spec.js
- spec/unit/pluginHandlers/common.spec.js
- spec/unit/pluginHandlers/handlers.spec.js
- spec/unit/prepare.spec.js
- templates/cordova/android_sdk_version
- templates/cordova/lib/list-emulator-images
use latest linting tools.
- updated @cordova/eslint-config@^4.0.0
- applied auto lint corrections
- apply manual changes to the `hasAndroidHome` variable.
- convert `var` to `let`
- `hoisted` the variable to the top of the function.
- `npm t`
- created project & added platform
- built platform
- ran application
> chore(npm): bump @cordova/eslint-config@^4.0.0

- lib/builders/ProjectBuilder.js
Android
Bill of Material (BoM) pattern simplifies the management of dependency versions (when there are multiple packages with shared dependencies).
https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import
A cordova plugin may want to use BoM to manage the versions of it's dependencies.
Currently there is no way to implement this:
- Package import can not be defined without a version defined
- No ability to import BoM platform
Example using Firebase BoM
https://firebase.google.com/docs/android/learn-more#bom
- `propertiesObj.systemLibs` regex - exclude any imports that contains `(` in it's package name
- Added `propertiesObj.bomPlatforms` - any value package which matches `platform("...")`
- Allow package to be imported without version. This will generate a warning in the …
> [Android] Added support for BoM imports

- lib/prepare.js
Restore `checkReqs` in `prepare.js`
In PR #1431, additional usage of `checkReqs` was added to `prepare.js`.
In PR #1154, the only usage of `checkReqs` was removed so the requirement was deleted.
Because of #1154 was merged first and #1431 was merged second, with no conflict, the test ended up failing on master. 
This PR just adds back the `require` statement.
`npm t`
> fix: restore checkReqs in prepare.js

- framework/src/org/apache/cordova/engine/SystemCookieManager.java
The `@SuppressWarnings("deprecation")` was added because there was some deprecated code for SDK <= 21, but it was removed some time ago, so it's no longer needed to suppress the deprecation warning.
> chore: Remove unneeded deprecated annotation

- framework/src/org/apache/cordova/engine/SystemCookieManager.java
- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
android
we are enabling file cookies even if AndroidInsecureFileModeEnabled is not enabled
accept file cookies only if AndroidInsecureFileModeEnabled is true
also suppress the warning caused by using that method 
removes two unused imports
closes https://github.com/apache/cordova-android/issues/1080
> fix: accept file cookies only if AndroidInsecureFileModeEnabled

- lib/prepare.js
- spec/unit/prepare.spec.js
Users may still use old tag.
Display a warning to migate to the new preference tag when `<splash>` tag is used.
This only checks for slash tags in `platform[name="android` as global tags could still be used in other platforms.
`cordova build`
> chore: display warning on deprecated <splash> tag usage

- lib/prepare.js
Ability to install platfrom from local git clone
If `require.resolve` fails to resolve`cordova-android`, it is coming from local dir..
`npm t`
`cordova build`
`cordova create`
`cordova platform add`
> fix: support installing platfrom from local git clone

- lib/prepare.js
Resolves #1454
Update the `destFile` variable to use the correct platform-specific path segment separators.
`npm t`
> fix(prepare): destFile path separator

- package.json
- types/index.d.ts
Affects TypeScript enabled projects only
Type definitions to allow programmatic control of the splashscreen are needed in `cordova-android` now that `cordova-plugin-splashscreen` was obsoleted as part of the Android 12 splash support.
Import the current type definitions from `cordova-plugin-splashscreen` and expose them for use within a typescript project.
I've imported this into an existing TypeScript-based application that has `cordova-plugin-splashscreen` removed, and ensured that TypeScript compilation produces no warnings or errors
> fix: import type definitions from obsolete cordova-plugin-splashscreen

- framework/src/org/apache/cordova/SplashScreenPlugin.java
Handler without arguments is deprecated, pass Cordova's Context mainLooper
> refactor: replace deprecated Handler constructor

- spec/fixtures/android_studio_project/gradle/wrapper/gradle-wrapper.properties
The default gradle version is 7.4.2 (https://github.com/apache/cordova-android/blob/606e9c482687dc3818186a02974a747cb183f73c/framework/cdv-gradle-config-defaults.json#L5)
But when creating new project, it still points to 7.1.1 until you run build that then updates the distribution url to 7.4.2
I think both versions should match.
> chore: Use gradle 7.4.2 distribution url

- lib/prepare.js
closes https://github.com/apache/cordova-android/issues/1475
`windowSplashScreenBrandingImage` is not valid, it should be `android:windowSplashScreenBrandingImage`.
All other values should also include the `android:`, but the support library allows to use them without the `android:` part, but since `windowSplashScreenBrandingImage` is not supported by the support library apps fail to compile.
This PR adds the `android:` prefix to the value so it gets added to the styles file with the prefix.
Needed to patch how the cdvConfigPrefKey is generated to strip the android: part of the themeKey
> fix: Add android prefix to windowSplashScreenBrandingImage

- framework/build.gradle
- framework/cordova-publish.gradle
Android
Currently when cordova-android is published to Maven, it lists no dependencies. However, `CordovaActivity` extends `AppCompatActivity` which requires that the AndroidX AppCompat library be available.
Marking AndroidX AppCompat as an API dependency (rather than an implementation/compile dependency) should cause the AndroidX AppCompat library to be installed when the cordova-android framework is added to the build.gradle of an existing Android application.
Tested publishing to my local Maven repository, and confirmed that dependencies are correctly captured in the pom.xml.
> fix: correctly flag API dependency on AppCompat for Maven

- framework/src/org/apache/cordova/SplashScreenPlugin.java
Configuring the status bar at startup no longer works on Android 13 if the splash screen has a configured `setOnExitAnimationListener`.
Current implementation creates an animation with no duration if FadeSplashScreen is false, and delays the hide of the splash screen for the configured amount on FadeSplashScreenDuration. 
But if FadeSplashScreen is false it should not have an animation listener and should not delay the splash screen hide.
related: https://github.com/apache/cordova-android/issues/1501
> fix: only do fadeout animation if FadeSplashScreen is true

- .github/workflows/ci.yml
> Update codecoverage reporting

- package.json
At the moment we have the lint script that tells you all the lint errors the code has, but you have to fix all the problems manually, which is tedious.
Since we are already using eslint for the linting, we can use the `--fix` parameter to automatically fix the errors (or at least most of them).
With this PR users will be able to run `npm run fmt` (I'm open for using other name), and fix the lint errors without having to manually change the code.
We could probably add this to all repositories that are already using eslint.
> chore: Add lint:fix script for fixing lint errors

- framework/cdv-gradle-config-defaults.json
Rationale:
API 22 & API 23 both account for an insignificant part of the market share. While API 24 - API 26 has similar market share, we felt that bumping to API 26 from API 22 is too large of a jump.
Legacy devices may be completely out of support by Google and may not be able to receive the latest webview version. As of writing, Chromium's latest tag shows they are using a Min SDK version of 24. (Ref: https://chromium.googlesource.com/chromium/src/+/refs/tags/113.0.5653.1/build/config/android/config.gni#46)
Based on AOSP emulators, API 24 (Android 7.0) will ship with Chrome 52 webview, which has good support for ECMAscript 2015 (ES6) (Ref: https://caniuse.com/?search=es6)
While in most cases, app users will likely have a modern webview vesion installed, this means you can be confident …
> feat!: Bump min SDK to 24

- framework/src/org/apache/cordova/CordovaInterfaceImpl.java
- framework/src/org/apache/cordova/PluginManager.java
Now that our Min SDK is 24, testing for >= N (API 24) and >= M (API 22) is obsolete as it will always be true. Simplify the codebase by removing the conditions and keeping only the API 24 or later codepath.
Manual build + npm test
> refactor: Removed obsolete version code checks

- framework/src/org/apache/cordova/engine/SystemWebViewEngine.java
Sister PR of https://github.com/apache/cordova-ios/pull/1300
Makes cordova-android honour the `InspectableWebview` preference in a similar fashion the iOS platform.
Like iOS, android will default to the original method of choosing if the inspecter should be enabled based on the module's debuggable flag. So if the preference is unset, the inspecter will be enabled on debug builds, and disabled on release builds.
If the preference is set and if, and only if the value is `"true"`, the webview inspecter will be forcefully enabled.
If the preference is set but is not `"true"` (including any invalid value), the webview inspector will be forcefully disabled.
Unlike iOS, Android has had the ability to independently control the inspecter programmatically for some time, so there is no Android OS …
> feat: InspectableWebview preference

- framework/cordova.gradle
- lib/check_reqs.js
- spec/unit/check_reqs.spec.js
Android
cordova-android 11.0.0 (since #1444) reports about `Android SDK: undefined` while `ANDROID_HOME` is set and `ANDROID_SDK_ROOT` is not.
```
cordova create hello com.example.hello HelloWorld
cd hello/
cordova platform add android@11.0.0
cordova build
```
with environment variables set for Java (`JAVA_HOME`) and Android (`ANDROID_HOME`, and no more `ANDROID_SDK_ROOT`)
results in a successful build but with wrong reporting during the first steps:
```
Checking Java JDK and Android SDK versions
ANDROID_HOME=C:\my\path\to\android-sdk (recommended setting)
ANDROID_SDK_ROOT=undefined (DEPRECATED)
Using Android SDK: undefined
```
- creating and building a blank project using local clone of my fork of cordova-android
- `npm run test`
> fix!: ANDROID_HOME is the new default, to check first and give advice

- test/androidx/app/build.gradle
- test/androidx/app/src/main/AndroidManifest.xml
Android Tests
https://github.com/apache/cordova-android/pull/1539 forgot to refactor the native test
With the newer AGP version, specifying the package id inside `AndroidManifest.xml` is deprecated and should be defined in the gradle file under `android.namespace`
Solves:
```
package="org.apache.cordova.unittests" found in source AndroidManifest.xml: /development/cordova/breautek/cordova-android/test/androidx/app/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, …
```
> fix(test): Native test namespace refactor

- framework/src/org/apache/cordova/CoreAndroid.java
We have 2 copies of an implementation of `getBuildConfigValue`, one inside `CoreAndroid` and another in `BuildConfig`.
The `BuildConfig` variant was directly migrated from our old deprecated `cordova-plugin-compat` package, so it is more likely that the `BuildConfig` variant is used more than the `CoreAndroid` version.
Added `@Deprecated` decorator for build compilation warning.
Add `@deprecated` JavaDoc for code editor hints and information on how to migrate.
Changed `CoreAndroid.getBuildConfigValue` to simply call and return the result of `BuildHelper.getBuildConfigValue`
Note that the screenshots are from a test app that was changed to use the deprecated API in the `MainActivity`. `MainActivity` template doesn't actually use the deprecated API.
`npm test` and manual testing.
> deprecate: CoreAndroid.getBuildConfigValue

- framework/src/org/apache/cordova/BuildHelper.java
Android
for example
if the Activity is not at the to  level of the package,like this. 
The package name of my project is com/yzq/cordovademo.  But I get  the `Unable to get the BuildConfig, is this built with ANT?` exception when I use the camera plugin.
We don't have to worry about the Activity hierarchy by getting the package name like `ctx.getApplicationInfo().packageName`
> fix(BuildHelper): get package name from ApplicationInfo

- framework/src/org/apache/cordova/CordovaWebViewImpl.java
- framework/src/org/apache/cordova/PluginManager.java
I don't anticipate breaking changes from this change, however it is a difference in behaviour since CoreAndroid won't be lazily loaded, therefore I've marked this commit has a breaking change.
Android / CoreAndroid plugin
CoreAndroid was lazily loaded via  `getPlugin` call. This can create a race condition in some situations, particularly 
with a new feature in the works: https://github.com/apache/cordova-android/pull/1574 where onRenderProcessGone may be invoked before anything gets a chance to call `getPlugin` for `CoreAndroid`.
In general, because this is **Core** plugin, I feel like it should always be loaded in, not lazily loaded in.
Inside `PluginManager`, I added a new public API: `addService(String serviceName, String className, bool onload)`.
The `addService(String serviceName, …
> fix!: Make CoreAndroid plugin instantiate on load

- lib/build.js
- lib/builders/ProjectBuilder.js
- package-lock.json
- package.json
- spec/unit/build.spec.js
- spec/unit/builders/ProjectBuilder.spec.js
Android / Gradle Argument pass through
gradle expects a specific usage which Cordova doesn't conform to.
```
$ gradle --help
USAGE: gradle [option...] [task...]
```
Currently we append the gradle arguments at the end of the gradle argument list, but option arguments are suppose to appear before the task(s).
Closes https://github.com/apache/cordova-android/issues/1604
Additionally, while testing I also discovered that arguments that requires multiple values (e.g. `--warning-mode all`) doesn't get passed through properly, yielding an argument array that looks like:
```javascript
[ "--warning-mode all" ]
````
when the expect array should look like:
```javascript
[ "--warning-mode", "all" ]
```
- Re-ordered the gradle argument array creation so that options appears before the task.
- …
> fix: Gradle Args parsing

- .github/workflows/ci.yml
NodeJS 20 has been released, may as well get some CI feedback on it.
> ci: Added NodeJS 20.x to the workflow matrix

- framework/src/org/apache/cordova/CordovaPlugin.java
- framework/src/org/apache/cordova/PluginManager.java
- framework/src/org/apache/cordova/engine/SystemWebViewClient.java
Android
This change allows more advanced handling of the webview render process termination. This can be useful for capturing additional information, or even conceivably allow the crash to be prevented should a plugin choose to.
Expose the [WebViewClient.onRenderProcessGone](https://developer.android.com/reference/android/webkit/WebViewClient#onRenderProcessGone(android.webkit.WebView,%20android.webkit.RenderProcessGoneDetail)) method down to plugins, and allow a plugin to interrupt the crash should it choose so.
I created the hello world cordova application and added a javascript call to load `chrome://crash` (recommended by Android docs as the best way to trigger a renderer crash).
> feat: add plugin hooks for WebViewClient.onRenderProcessGone

- lib/Api.js
- lib/run.js
- spec/unit/Api.spec.js
- spec/unit/run.spec.js
n/a
Support calling for listTarget on the PlatformAPI.
Will be used by Cordova CLI/Lib 12
Added `listTargets` on platform api and added supporting methods in the `run.js` file
`npm t`
> feat: add listTarget api

- lib/prepare.js
- package-lock.json
- package.json
- spec/unit/prepare.spec.js
Android
fixes #1616 
cordova-android 12 introduces support for monochrome icons. It was intended for it to be optional.
However due to a faulty check, if you didn't supply the monochrome property, adaptive icons will not be written out.
I've corrected the check. Additionally I added the `dedent` package which is a string template formatter so that
we can more easily format some of our inline templates to make it easier to read.
I've also added a warning for when the monochrome property is given without the required adaptive properties. Tests were added to assert that icons are written as expected with and without the monochrome property as well as the warning is emitted.
There is one caveat, the warning in practice isn't seen by the user because the CLI ends up kicking out earlier via …
> fix(GH-1616): Fix monochrome checks

- lib/config/CordovaGradleConfigParserFactory.js
- package-lock.json
n/a
- Remove audit warnings
- Latest sub-dependencies for development testing
- Rebuilt `package-lock.json`
- Apply lint fix. Remove file starting new line.
`npm t`
> chore: rebuild package-lock w/ lint corrections

- framework/src/org/apache/cordova/CordovaWebView.java
- package-lock.json
- package.json
Bump version for next major (SDK 34)
Bump Cordova-Android package version to 13.0.0-dev
`npm t`
> chore: bump version 13.0.0-dev

- framework/src/org/apache/cordova/engine/SystemWebViewClient.java
Ionic webview plugin has had this preference for a few years, it makes possible for service worker requests to go through the asset loader.
> feat: Add ResolveServiceWorkerRequests preference

- lib/prepare.js
Android
Adds support for the more general `SplashScreenBackgroundColor` preference.
Sets the splashscreen background based on the following options (in order):
* `AndroidWindowSplashScreenBackground` preference
* `SplashScreenBackgroundColor` preference
* `BackgroundColor` preference
* `#ffffff` hardcoded
Didn't seem like there were any existing unit tests for the splashscreen stuff, so I didn't update any tests.
> feat(splash): Support SplashScreenBackgroundColor preference

- .github/workflows/ci.yml
- framework/src/org/apache/cordova/CordovaActivity.java
- framework/src/org/apache/cordova/CordovaClientCertRequest.java
- framework/src/org/apache/cordova/CordovaDialogsHelper.java
- framework/src/org/apache/cordova/CordovaHttpAuthHandler.java
- framework/src/org/apache/cordova/CordovaInterfaceImpl.java
- framework/src/org/apache/cordova/CordovaWebViewImpl.java
- framework/src/org/apache/cordova/CoreAndroid.java
- framework/src/org/apache/cordova/NativeToJsMessageQueue.java
- framework/src/org/apache/cordova/engine/SystemCookieManager.java
- framework/src/org/apache/cordova/engine/SystemExposedJsApi.java
- framework/src/org/apache/cordova/engine/SystemWebChromeClient.java
- spec/fixtures/android_studio_project/app/src/main/AndroidManifest.xml
- test/androidx/app/src/androidTest/java/org/apache/cordova/unittests/BackButtonMultipageTest.java
- test/androidx/app/src/androidTest/java/org/apache/cordova/unittests/ErrorUrlTest.java
- test/androidx/app/src/androidTest/java/org/apache/cordova/unittests/MessageChannelMultipageTest.java
- test/androidx/app/src/main/AndroidManifest.xml
- test/androidx/app/src/main/java/org/apache/cordova/unittests/EmbeddedWebViewActivity.java
CodeQL scanning in CI can help identify bugs and security issues with the library.
* Added CodeQL scanning with default options as part of CI.
* Include fixes
* Ran this in my fork, confirmed that CodeQL results showed up under security scanning
* Applied some small fixes
> ci: Set up CodeQL analysis w/ fixes

- templates/project/AndroidManifest.xml
From API 13
To avoid app restart on connecting/disconnecting BT keyboard in some devices. Issue is faced by many and is also described here: https://stackoverflow.com/questions/25735227/bluetooth-keyboard-will-cause-activity-destroy-and-recreate/27238892#27238892
There is no easy way to extend this using config's.
In some devices (especially pixel) connecting with BT keyboard is resulting in application being restarted. The existing "keyboard" seems to be not sufficient as in this case it was triggering "navigation" change.
Tested on problematic devices by connecting and disconnecting keyboards
> Fix for app restart when BT keyboard is connected in some devices

- README.md
README still stated that JDK 11 is required, when cordova-android@13 now requires JDK 17.
> fix(docs): Incorrect JDK requirement stated in README

- templates/project/app/build.gradle
Update library dependencies
- Use `kotlin-stdlib`
- Added constraints to prevent `kotlin-stdlib-jdk7` and `kotlin-stdlib-jdk8` from being installed by other libraries, as `kotlin-stdlib` is already included.
- `npm t`
- Build Cordova sample application.
- Tested on Android Studio - Ladybug
> feat!: use kotlin-stdlib instead of kotlin-stdlib-jdk*

- lib/create.js
Able to build project when platform was installed with `--link` 
The `cdv-gradle-config.json` file was not being created when the `--link` flag was used during platform add.
This PR moved the creation logic to ensure that `cdv-gradle-config.json` was created with or without  `--link`.
- `npm t`
- Build Cordova sample application.
- Tested on Android Studio - Ladybug
> fix: creation of cdv-gradle-config.json w/ --link flag

- framework/src/org/apache/cordova/CordovaPlugin.java
It is recommended to use `pluginInitialize` and not `initialize`.
At one point `initialize` was deprecated but later the flag was removed. This PR is re-adding the flag to make aware that the `initialize` method is deprecated and will be removed in a future release. Plugin developers should switch to `pluginInitialize`.
The question about this originated from doc repo: https://github.com/apache/cordova-docs/issues/1386
`npm t`
> feat!: deprecate CordovaPlugin's method initialize

- lib/builders/ProjectBuilder.js
- lib/check_reqs.js
- lib/config/CordovaGradleConfigParser.js
- lib/create.js
- lib/emulator.js
- lib/env/java.js
- lib/pluginHandlers.js
- lib/prepare.js
- lib/utils.js
- package-lock.json
- package.json
- spec/e2e/e2e.spec.js
- spec/unit/builders/ProjectBuilder.spec.js
- spec/unit/check_reqs.spec.js
- spec/unit/create.spec.js
- spec/unit/emulator.spec.js
- spec/unit/pluginHandlers/common.spec.js
- spec/unit/pluginHandlers/handlers.spec.js
- spec/unit/prepare.spec.js
- test/run_java_unit_tests.js
n/a
Replace `fs-extra` dependency with node internals `node:fs`
Remove `fs-extra` and updated code to require and use `node:fs` APIs.
`npm t`
> refactor: replace fs-extra with node:fs

- lib/check_reqs.js
As of https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high Cordova produce unrecognized error on Windows.
Fixes: https://github.com/apache/cordova-cli/issues/456
> feat: Account for Node security patch

- lib/prepare.js
- spec/unit/prepare.spec.js
- templates/project/res/values/themes.xml
- Disable the Edge-to-Edge setting that SDK 35 enabled by default.
- Allow users to opt-in to the Edge-to-Edge feature with a flag.
In the next Cordova-Android release, we will temporarily disable the Edge-to-Edge feature to maintain the same behavior that existed previously. The new feature appears to have issues with safe-area-*.
When setting `viewport-fit` to `auto` or `contain`, the content will render behind the safe-area which is believed to be an unintended behavior. iOS for example will automatically render the content below the statusbar. 
- Added theme flag `android:windowOptOutEdgeToEdgeEnforcement` and default to `true`
- Added preference flag `AndroidEdgeToEdge` to allow changing of the theme flag
- When `AndroidEdgeToEdge` is set to `true`, …
> feat: add AndroidEdgeToEdge preference & theme flag

- framework/cdv-gradle-config-defaults.json
- spec/unit/builders/ProjectBuilder.spec.js
n/a
- Use latest Gradle
- [Resolve FileLockCommunicator compatible issue with macOS 15.1 firewall](https://github.com/gradle/gradle/issues/31245)
Update default version and test to 8.13
- `npm t`
- Build test
> feat: bump gradle to 8.13

- lib/builders/ProjectBuilder.js
Copy the gradle wrapper files from `platforms/android/tools` to `platforms/android`
Fixes #1760
Updated install step to just copy all the gradle files up one directory.
- Created a Cordova Project
- Added Platform
- Built Android Platform
> fix: copy gradle wrapper from tools to platform root dir

- package-lock.json
- package.json
- Update npm dependencies
- Rebuild package-lock.json
Bump packages to:
- nyc@17.1.0
- which@5.0.0
- semver@7.7.1
- jasmine@5.6.0
- android-versions@2.1.0
- cordova-common@5.0.1
- fast-glob@3.3.3
- nopt@8.1.0
- `npm t`
- `cordova platform add android`
> dep!: bump npm packages

- lib/check_reqs.js
Resolves #1792
Before Android Studio 3.5, Gradle was bundled with the IDE.
In the past, for Windows environments, we attempted to locate the Android Studio installation path to use its bundled Gradle executable.
However, Cordova has not supported old versions of Android Studio for a long time, making this logic obsolete. Additionally, past release announcements have indicated increasing Android Studio requirements:
- Cordova-Android 13 required a minimum of Android Studio Jellyfish.
- Cordova-Android 14 required a minimum of Android Studio Ladybug.
Documentation also stated that since Cordova-Android 6.4.0, a system-level Gradle installation is required. Cordova would then uses this to generate the project-level Gradle wrapper.
Given these changes, this PR will remove the outdated …
> fix(windows): get gradle path with which command

- lib/builders/ProjectBuilder.js
Fix an issue mentioned in a [discussion thread](https://github.com/apache/cordova/discussions/530#discussioncomment-12605698).
1. Ensure that Cordova-Android properly creates `config.properties`.
2. Ensure that `java.home` is set correctly:
1. Check and use the `CORDOVA_JAVA_HOME` environment variable.
2. If `CORDOVA_JAVA_HOME` is missing, fall back to `JAVA_HOME`.
3. If neither is set, remove the `java.home` property (if previously set), allowing Android Studio to display a warning and configure its internal Java automatically.
3. Copy the `tools/.gradle` directory up one level.
**Note:** Step 2.3 should not occur under normal conditions, but was included as a safeguard. When running `cordova build`, if `JAVA_HOME` is missing, its expected to not continue as its apart of the requirement …
> fix: configure gradle java.home

- lib/pluginHandlers.js
Support ability to uninstall multiple defined assets in a plugin and match recent changes with iOS platform.
Matched logic with iOS
Adding and uninstalling plugins
> fix(plugins): handle uninstalling multiple plugin assets

- lib/pluginHandlers.js
- spec/unit/pluginHandlers/common.spec.js
- spec/unit/pluginHandlers/handlers.spec.js
Update Android's plugin handler to be a bit more closer to iOS's plugin handler.
- Renamed `removeFile` to `removeFileF`. (The trailing `F` refers to the `force` flag that is used.)
- `npm t`
> fix(plugins): rename & match removeFileF logic with other platforms

- spec/unit/pluginHandlers/handlers.spec.js
Cleanup test test spec.
Remove deprecated flag `android_studio` from test spec.
- `npm t`
> test(plugins): remove old deprecated android_studio option

- .gitignore
- framework/cordova.gradle
- test/run_java_unit_tests.js
Resolves #1759
Use repos defined in `repositories.gradle` for the `cordova.gradle` dependencies
Replaced:
```groovy
repositories {
google()
mavenCentral()
}
```
With:
```groovy
apply from: 'repositories.gradle'
repositories repos
```
- `npm t`
- Created and built sample Cordova app with changes
> fix: apply repositories.gradle for cordova.gradle dependencies

- lib/builders/ProjectBuilder.js
This change resolves the Node.js deprecation warning DEP0176:
> fs.F_OK is deprecated, use fs.constants.F_OK instead
The warning appears when building projects with recent versions of Node.js (v20.8.0+).
No open issue was found for this warning at the time of writing.
Replaced usage of the deprecated `fs.F_OK` with `fs.constants.F_OK` in `cordova-android/lib/builders/ProjectBuilder.js`.
This change aligns with the Node.js recommendation since v6.3.0.
- Verified that the build still completes successfully without functional issues.
- Confirmed that the DEP0176 deprecation warning is no longer emitted during build.
- `npm test`
> fix: replace deprecated fs.F_OK with fs.constants.F_OK

- lib/prepare.js
- templates/project/build.gradle
Android
Useful development tool for core android & plugin developers
Introduces a new `AndroidShowDeprecations` preference flag, which when `true` it will enable deprecation prints in the build output. By default, the flag is false.
See https://github.com/apache/cordova-docs/pull/1424 for documentation
Manual testing.
> feat: AndroidShowDeprecations preference flag

- framework/src/org/apache/cordova/CoreAndroid.java
Android
Android API 36 will crash on hardware back button presses due to breaking changes noted [here](https://developer.android.com/about/versions/16/behavior-changes-16#predictive-back)
Basically intercepting key events using `onDispatchKeyEvent` no longer works for back button. The return value is ignored for back key events and the system will use the system default action, in addition to whatever code is being triggered by `onDispatchKeyEvent`.
On API 36+, the predictive back feature may take you out of your app, and if it does, the activity may be destroyed. We have key event listeners that will send events to the webview, but in this circumstance the webview will be unusable leading to a crash.
To prevent system behaviour, the OnBackInvokedCallback needs to be registered with the …
> fix(android): Back button override on API 36+

- framework/src/org/apache/cordova/PluginManager.java
In `instantiatePlugin`, `Class.getInstance` was called, but is [deprecated since Java 9](https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#newInstance--). Instead `Class.getDeclaredConstructor().newInstance()` should be called.
Android
Resolving deprecation warnings for cordova-android
> fix: Deprecation warning in PluginManager for using Class.newInstance
