apache/cordova-android

bin/templates/cordova/lib/emulator.js
bin/templates/cordova/lib/exec.js
bin/templates/cordova/lib/retry.js

Adding lib/retry.js for retrying promise-returning functions. Retrying 'adb install' in emulator.js to work around it hanging sometimes.
Related Android bug: https://code.google.com/p/android/issues/detail?id=10255

CB-9119 Fixing intermittent 'adb install' hanging issue

---

.travis.yml

https://issues.apache.org/jira/browse/CB-9260

CB-9260 Install Android-22 on Travis-CI

---

bin/templates/cordova/lib/appinfo.js
bin/templates/cordova/lib/device.js
bin/templates/cordova/lib/emulator.js

This fixes [CB-9557](https://issues.apache.org/jira/browse/CB-9557) and probably [CB-8834](https://issues.apache.org/jira/browse/CB-8834)
I've also caught the issue, described on SO (http://stackoverflow.com/questions/26794862/failure-install-failed-update-incompatible) which is resolved by this PR as well.

CB-9557 Fixes apk install failure when switching from debug to release build

---

bin/lib/create.js

JIRA issue: [CB-9880](https://issues.apache.org/jira/browse/CB-9880)

CB-9880 Fixes platform update failure when upgrading from android@<4.1.0

---

bin/templates/cordova/lib/device.js
bin/templates/cordova/lib/emulator.js

JIRA: [CB-10157](https://issues.apache.org/jira/browse/CB-10157)

CB-10157 Uninstall app from device/emulator only when signed apk is already installed

---

bin/templates/cordova/lib/run.js

See [CB-10421](https://issues.apache.org/jira/browse/CB-10421)

CB-10421 Fixes exception when calling run script with --help option

---

bin/templates/cordova/lib/emulator.js

The `emulator.js` script waits forever for the emulator to boot. If the emulator gets stuck, it will never terminate. The reason for adding this timeout is that the Android emulator on Windows occasionally hangs while booting up. This causes problems in our CI, where the run step would go on forever until buildbot eventually cut it off (see [here](https://ci.apache.org/builders/cordova-android-win/builds/1588/steps/running-tests/logs/stdio) for an example run). I have an upcoming PR for cordova-medic that switches from using `cordova run` to start the emulator to requiring this script directly so that we can add retry logic for the emulator start. I don't think it really makes sense to expose the timeout option in the CLI itself, so this PR does not alter the CLI's behavior at all (it …

CB-10510: Add an optional timeout to emu start script

---

bin/templates/cordova/lib/emulator.js
bin/templates/cordova/lib/run.js
package.json
spec/unit/run.spec.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10628)

CB-10628 Fix emulate android --target

---

bin/templates/cordova/lib/list-devices
bin/templates/cordova/lib/list-emulator-images
bin/templates/cordova/lib/list-started-emulators

[Jira issue](https://issues.apache.org/jira/browse/CB-10669)

CB-10669 cordova run --list cannot find 'adb'

---

bin/templates/cordova/lib/build.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10862)

CB-10862 Cannot set minsdkversion

---

framework/src/org/apache/cordova/CallbackContext.java

This reverts commit 1b43bc99a1c50e5ab30347ec9ca5af8cf22d3e85.

Revert "CB-10881: Logging to further investigations"

---

bin/templates/cordova/lib/pluginHandlers.js

[Jira issue](https://issues.apache.org/jira/browse/CB-11015)

CB-11015 Error adding plugin with gradle extras

---

bin/templates/cordova/lib/emulator.js

Please find the details in the [Jira issue](https://issues.apache.org/jira/browse/CB-11133).

CB-11133 Handle android emulator start failure

---

bin/templates/cordova/lib/emulator.js

CB-11133 Handle android emulator start failure (reverted from commit abcaee24f9bd0e680f8d06ced5e0d363d63cffb7)

CB-11163 Android Builds are failing in CI

---

bin/templates/project/assets/www/cordova.js
cordova-js-src/exec.js
spec/e2e/create.spec.js

Useragent Regexp result is null in node environment - add a check for it
Updated cordova-js
[CB-11869](https://issues.apache.org/jira/browse/CB-11869)

CB-11869 Fix cordova-js android exec tests

---

bin/templates/cordova/Api.js

android
catches possible error and outputs message
jshint, ran tests

CB-11999 add message, catch exception if require fails

---

README.md
test/README.md

Please review @infil00p.
FYI @dpogue @purplecabbage @shazron @jcesarmobile @alsorokin.

CB-12859: document how to run the native tests

---

bin/templates/cordova/lib/prepare.js

This is the Android Platform API support side of https://github.com/apache/cordova-lib/pull/453.

[CB-10916] Support display name for Android

---

framework/project.properties

Updates Cordova so it creates Android O projects by defualt
* Passes CI (somehow, magic)
* Ran Hello World
* Ran mobile-spec
- [x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.

CB-13177: Updating to API Level 26

---

appveyor.yml

Update appveyor to support node 8

CB-13501 : update appveyor to support node 8

---

.travis.yml
appveyor.yml
bin/templates/cordova/lib/builders/GradleBuilder.js
bin/templates/cordova/lib/check_reqs.js
bin/templates/project/build.gradle
test/app/build.gradle
test/build.gradle
test/gradle/wrapper/gradle-wrapper.properties

Android
Fixes build errors caused by the installation/update of the latest Android Studio
Built a project, it compiled!

CB-13289: This fixes the Cordova-Android build on cordova-android 6.x

---

framework/build.gradle
framework/gradle/wrapper/gradle-wrapper.properties

Cordova-Android
Fixes the Framework Gradle so that we can upload the AAR
Ran gradle bintrayUpload

CB-13558: Upgrading the gradle so we can upload the AAR

---

test/app/build.gradle
test/build.gradle

Android
Bumps MinSDK to 19 on the Tests, bumps plugin versions on Test
Tested in Android Studio 3.0.1

CB-12914: Test needs SDK bumps

---

bin/templates/project/app/build.gradle
bin/templates/project/build.gradle
framework/project.properties
test/app/build.gradle

CB-13724: Bump Target SDK to API 27

---

bin/templates/project/app/build.gradle

Update comments in build.gradle

---

test/README.md

improve test readme

---

bin/templates/project/gitignore

It would be nice for this to be part of the next major release for Cordova 9 (apache/cordova#10).

Ignore Android Studio .idea files in project

---

spec/unit/Api.spec.js
spec/unit/check_reqs.spec.js
spec/unit/create.spec.js

A replica of https://github.com/apache/cordova-lib/pull/619 for this repository.

Simplify and fix promise handling in specs

---

package.json

Let's us use the latest Jasmine features like e.g. `resolveTo` and `rejectWith`.

Update jasmine to 3.5.0

---

framework/src/org/apache/cordova/CordovaBridge.java

This judgment condition has no use.
Delete unnecessary judgments. 
Can improve program execution efficiency

Optimization code

---

.reviewboardrc
LICENSE
NOTICE
README.md
RELEASENOTES.md

Apply various cleanup changes to doc related files
* update LICENSE year
* update third-party appended licenses
* update NOTICE year & format
* yse correct CI badges on README.md
* remove extra markdown from RELEASENOTES.md

chore: various cleanup

---

.gitignore
package-lock.json

Add `package-lock.json`
Requires #953, #954, #955 
- `npm t`

chore(npm): add package-lock.json

---

package.json

Android
Fixes #913 (And potentially other issues, however not yet confirmed)
APIs are used that requires a Node minor release of `10.10.0`.
https://github.com/apache/cordova-android/blob/cdcb4ddcd9b9b42facea7460f2f6309a4ac8d6fc/bin/templates/cordova/lib/builders/ProjectBuilder.js#L77
Do note that this is already released in verison `9.0.0`.
Increase `package.json` node engine to `>= 10.10.0`
Ran `npm test`.

fix: Reflect true minimum required NodeJS

---

bin/templates/cordova/lib/builders/ProjectBuilder.js
bin/templates/project/app/build.gradle
test/android/wrapper.gradle
test/androidx/wrapper.gradle

Android
Gradle version to 6.8.3

feat: upgrade gradle@6.8.3

---

bin/templates/project/build.gradle
test/android/build.gradle

Android
feat: upgrade kotlin@1.4.31

feat: upgrade kotlin@1.4.31

---

bin/templates/project/app/build.gradle
bin/templates/project/build.gradle
framework/build.gradle
spec/fixtures/android_studio_project/build.gradle
test/android/build.gradle
test/androidx/build.gradle

Android
feat: upgrade gradle-plugin@4.1.3

feat: upgrade gradle-plugin@4.1.3

---

bin/templates/project/app/build.gradle
bin/templates/project/app/repositories.gradle
bin/templates/project/build.gradle
bin/templates/project/repositories.gradle
framework/build.gradle
framework/repositories.gradle

This is to correct a big rebase booboo.
Original PR and credit goes to https://github.com/apache/cordova-android/pull/867

feat: add custom repositories support

---

bin/templates/project/app/build.gradle
bin/templates/project/build.gradle
framework/build.gradle
spec/fixtures/android_studio_project/build.gradle
test/android/build.gradle
test/androidx/build.gradle

Reverts apache/cordova-android#1175
Sorry, it seems some people do not trust that this follows semver and feels it may not fit a minor release.
We will revert this PR and would like it resubmitted for the major release.

Revert "feat: upgrade gradle-plugin@4.1.3"

---

bin/templates/project/build.gradle
test/android/build.gradle

revert: feat: upgrade kotlin@1.4.31 #1176

---

bin/templates/cordova/lib/builders/ProjectBuilder.js
bin/templates/project/app/build.gradle
bin/templates/project/build.gradle
framework/build.gradle
spec/fixtures/android_studio_project/build.gradle
test/android/build.gradle
test/android/wrapper.gradle
test/androidx/build.gradle
test/androidx/wrapper.gradle

This PR Reverts apache/cordova-android#1079 and brings everything back to rel/9.0.0

Revert "[Frequent Updates] Gradle 6.6.1 & Android Gradle Plugin 4.0.1 & com.jfrog.bintray.gradle 1.8.5"

---

bin/templates/project/app/repositories.gradle
bin/templates/project/repositories.gradle
framework/repositories.gradle

Added missing header licenses
- N/A

chore: add missing header license

---

bin/templates/project/app/build.gradle
bin/templates/project/build.gradle
framework/build.gradle
spec/fixtures/android_studio_project/build.gradle
test/android/build.gradle
test/androidx/build.gradle

* Reintroduces changes that were reverted to not cause issues with 9.1.0 release.
* Changes were cherry-picked to retain original author.
* Original PR Work:
* https://github.com/apache/cordova-android/pull/1079
* https://github.com/apache/cordova-android/pull/1175
* Upgrades Android Gradle Plugin to 4.1.3
**PR is based off PR #1197 and should be rebased after merged.**

feat!: upgrade android gradle plugin@4.1.3

---

bin/templates/project/build.gradle
framework/build.gradle
test/android/build.gradle

* Reintroduces changes that were reverted to not cause issues with 9.1.0 release.
* Changes were cherry-picked to retain original author.
* Original PR Work:
* https://github.com/apache/cordova-android/pull/1176
* Upgrades Kotlin to 1.4.31
**PR is based off PR #1199 and should be rebased after merged.**

feat!: upgrade kotlin@1.4.31

---

bin/templates/project/app/build.gradle
bin/templates/project/build.gradle
framework/build.gradle
spec/fixtures/android_studio_project/build.gradle
test/androidx/build.gradle

feat: Upgrade gradle plugin to 4.2.1

---

framework/src/org/apache/cordova/CordovaWebView.java
package-lock.json
package.json

Update version to target a patch release of 10.0.1
- n/a

chore: set version for patch release 10.0.1-dev 

---

framework/cordova-publish.gradle

Add missing settings for signing and publishing to Maven Central
- Published 10.0.0 to Maven Central

fix: maven-publish setup

---

package-lock.json
package.json

n/a
Prepare for next major release
bump package and package-lock
n/a

chore: bump for next major 11.0.0-dev

---

package-lock.json
package.json

Latest Jasmine Test Framework w/ rebuilt package-lock
`npm t`

dep: bump jasmine@4.2.1 w/ package-lock rebuild

---

.github/workflows/ci.yml

Use relaxed version of codecov/codecov-action to fetch latest minors and patch fixes.
Replace strict version with `codecov/codecov-action@v3`
n/a

ci(workflow): update codecov/codecov-action@v3

---

framework/src/org/apache/cordova/CordovaWebView.java
package-lock.json
package.json

Prepare for next major release
Bump `package`, `package-lock`, and `CordovaWebView`
n/a

chore: prepare package version for next major 12.0.0-dev

---

package-lock.json
package.json

Use latest cordova-common release for next major
bump cordova-common@5.0.0
`npm t`

dep(npm)!: bump cordova-common@5.0.0

---

package-lock.json
package.json

Use latest node modules
Dependencies:
- `android-versions@^1.8.1`
- `fast-glob@^3.2.12`
- `fs-extra@^11.1.0`
- `nopt@^7.0.0`
- `semver@^7.3.8`
- `which@^3.0.`
Dev Dependencies:
- `jasmine@^4.5.0`
`npm t`

dep(npm)!: bump acceptable modules w/ rebuilt package-lock

---

lib/build.js
lib/check_reqs.js
lib/prepare.js
package-lock.json
package.json

n/a
Use latest npm dependencies.
Bumped:
- fs-extra@11.1.1
- nopt@7.1.0
- @cordova/eslint-config@5.0.0
- jasmine@4.6.0
Applied ESlint auto corrections.
Rebuilt package-lock.json.
`npm t`

dep: bump npm dependencies

---

.github/workflows/ci.yml
.github/workflows/release-audit.yml

all
Improve CI.
* Fix errors when dependabot PRs try to run tests in CI
* Ran in CI, tests pass

chore(ci): Fix dependabot PR failures

---

package-lock.json
package.json

n/a
Prepare next major release
Bump version 14.0.0
n/a

chore: bump 14.0.0-dev

---

.gitignore

Added missing gitignore
Added `/test/androidx/build` to `.gitignore`
n/a

chore: add androidx build test to gitignore

---

framework/src/org/apache/cordova/CordovaWebView.java
package-lock.json
package.json

Bump Platform package version for next major
Bump version to 15.0.0-dev
n/a

chore: bump 15.0.0-dev

---

.github/workflows/release-audit.yml

Update Release Audit Workflow to use latest RAT Action tool.
n/a

ci(release-audit): use latest apache-rat-action
